### ISSUE TITLE
Menüband und Megamenü

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#1]
Unterkategorien haben die falsche Schriftgrösse oder Art, im im Bereich Geschäftsfelder fehlen die Icons, "Pfeil" fehlt - bitte nochmals mit der Vorlage vergleichen und überarbeiten. Bitte ausserdem auch die Farben prüfen ob sie mit der Vorlage übereinstimmen (hellblau).

![grafik](https://user-images.githubusercontent.com/122005698/218455049-eaec02b3-1964-4384-8daf-ca676c2c2c23.png)
![grafik](https://user-images.githubusercontent.com/122005698/218455205-0cba68b8-2344-41a3-b2a4-13b6b0ae7fbf.png)

**Comment by mguddelmoni** [comment]
Icons und Pfeil sind implementiert.
