### ISSUE TITLE
Schriftgrössen: Ganze Website

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#10]
An sich sollten die Schriftgrössen Responsive sein, heisst auf Mobile kleinere Schriften als auf dem Desktop.

Auch bei den Titeln sollte man schauen, dass man diese auf ein Level bringt, welche über möglichst viele Gerätegrössen gut aussieht. 

https://user-images.githubusercontent.com/85960512/219322589-75c6f468-2a8c-4d41-ab9e-4d6e556c4aa3.mp4

**Comment by mguddelmoni** [comment]
Habe nun auch die Grundschrift mit Mediaqueries versehen. Somit werden nicht nur die Überschriften dynamisch gesetzt
