### ISSUE TITLE
Angepasste Elemente auf älteren Seiten

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#100]
Kann es sein, dass Änderungen auf bereits bestehende Seiten nicht übernommen würden bei einzelnen Elementen?

Im Vergleich sehen die Karten, Header auf der ersten und älteren Seite anders als auf der zweiten neueren. Muss ich alle bestehenden Seiten nochmals neu machen? Das kann nicht sein....

Alte Seite: https://abonax2023.visions.page/manager/?a=resource/update&id=131
![image](https://user-images.githubusercontent.com/122005698/236853017-6cc54023-138f-4a08-8a87-4321db71eba9.png)

Neue Seite: https://abonax2023.visions.page/angebot/services/energiewirtschaft-neu.html
![image](https://user-images.githubusercontent.com/122005698/236853095-0492081a-f430-4d4e-a6fd-121a09c706f4.png)

**Comment by christoph-menzi** [comment]
Du musst nur die Headline anpassen auf h5.

![image](https://user-images.githubusercontent.com/109087392/236855947-f2dad175-cb40-4e16-8251-cd3c696d1941.png)

Und die Spaltebreite auf 5 und 7 stellen
![image](https://user-images.githubusercontent.com/109087392/236856431-ff1256cb-059b-42a8-8709-6eccf8af6167.png)

**Comment by christoph-menzi** [comment]
ich habe es Dir kurz gemacht. https://abonax2023.visions.page/angebot/produkte/zev.html
