### ISSUE TITLE
Auswahl der Referenzen pro Seite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#101]
Gibt es eine Möglichkeit, dass wir die Referenzen pro Seite jeweils auswählen können? Momentan wird ja nur ein Element hinzugefügt und die Referenzen werden automatisch angezeigt. Welche Logik ist dahinter? Werden einfach die letzten 3 bzw. 6 Referenzen angezeigt?

**Comment by christoph-menzi** [comment]
Ist noch nicht definiert wie es genau funktionieren soll.
Im Normfallfall wären einfach die 3 aktuellsten Referenzen die angezeigt werden. Eine manuelle Auswahl der Referenzen wäre aber denkbar.

**Comment by Riccardalina** [comment]
Das würden wir gerne so umsetzen. Wie ist das Vorgehen, was benötigt ihr von mir?

**Comment by mguddelmoni** [comment]
Es gibt nun ein Auswahlelement mit dem man die Referenzen zusammenstellen kann
![Bildschirmfoto 2023-07-11 um 14 01 56](https://github.com/Riccardalina/Abonax-Website/assets/64895942/3f47bdf9-0842-4385-b1b0-b0ee7f9f5466)
