### ISSUE TITLE
Element Call to action: Link öffnen in neuem Fenster

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#102]
Die Funktion "Link öffnen in neuem Fenster" funktioniert nicht.

Beispiel hier unter der Kategorie "Klickstrecken": https://abonax2023.visions.page/angebot/produkte/website-landingpage.html

**Comment by christoph-menzi** [comment]
Auf dieser Seite gibt es aber nur Verlinkungen zum Mail. Das geht nicht mit öffnen in neuem Fenster. Das wird dann (wenn ein Mail-Client im OS definiert ist, z.B. Outook) direkt mit dem Mail-Programm verbunden.
