### ISSUE TITLE
Karten

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#103]
Bild Crop funktioniert hier wieder irgendwie nicht

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/efff1dcb-dd43-4761-973f-838c29db4414)

Seite: https://abonax2023.visions.page/angebot/fachbereiche/elektromobilitaet.html

**Comment by christoph-menzi** [comment]
Ist gefixt.
