### ISSUE TITLE
Link Datenschutz bei Kontaktformular

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#104]
Wie kann ich den Link hier anpassen:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/811aace4-6248-4a59-88b8-907fbf929dc1)

**Comment by christoph-menzi** [comment]
Das Formular ist von uns programmiert. Ich müsste das anpassen. Wohin soll es verlinkt werden? Welches Dokument (ID)?

**Comment by mguddelmoni** [comment]
Die Seite befindet sich hier:
https://abonax2023.visions.page/manager/?a=resource/update&id=144

**Comment by mguddelmoni** [comment]
Ich habe sie nun angepasst auf 
https://abonax2023.visions.page/manager/?a=resource/update&id=49
