### ISSUE TITLE
Element: CTA mit Hintergrundbild

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#105]
Das Bild hier ist verpixelt obwohl es eigentlich eine gute Qualität haben sollte:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/2560bd61-a799-4dd6-bc67-5c7dcbfd0c5d)

Link: https://abonax2023.visions.page/manager/?a=resource/update&id=60

**Comment by christoph-menzi** [comment]
Bild wird neu auf 1700px berechnet. Bis dato war es auf 940px
