### ISSUE TITLE
Logo Konfigurator

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#107]
Ich verstehe die Logik des Konfigurators noch nicht ganz. ich habe nun neue Logos hinzugefügt. werden die nun automatisch auf allen seiten gesetzt und aktualisiert? hier beispielsweise werden sie nicht angezeigt. es wäre gut, wenn ich für jede seite bestimmen könnte, welche logos ich anzeigen möchte. 

https://abonax2023.visions.page/angebot/fachbereiche/energiewirtschaft.html

**Comment by christoph-menzi** [comment]
Die Logos werden auf der Home Seite erfasst:

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/cef22388-198c-43bf-8289-e14e5c66d3fd)

Und auf den Unterseiten kann man die Logos dann aktivieren / deaktivieren.
![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/638a0734-0c18-4d34-9a0b-f608ce5d3f11)

Die Grundidee ist: Logos an einem Ort erfassen, auf den jeweiligen Unterseiten dann anzeigen lassen.

**Comment by Riccardalina** [comment]
ok aber das problem ist hier, dass jedesmal wenn ich ein neues logo erfasse, dieses automatisch auf allen anderen seiten, die dieses element haben, auch erscheint. wenn dann müsste es doch so sein, dass ich die logos nur manuell pro seite hinzufügen kann. es ist sehr unpraktisch, wenn ich das neue logo auf allen seiten, auf denen das element angezeigt wird, jedesmal manuell auf inaktiv setzen muss.

**Comment by christoph-menzi** [comment]
Nein, das Logo MUSS freigeschaltet werden. Default ist immer "nein".

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/7b13bb86-c0ed-46e2-bc30-c6d048bc8636)

**Comment by mguddelmoni** [comment]
Du kannst jedes Logo auf jeder Seite separat aktivieren / deaktivieren
Dies musst du auf der jeweilgen Seite im Logo Konfigurator machen.
Gehe auf die entsprechende Seite >> Logo Konfigurator >> Bearbeiten >> Aktivieren Ja/Nein
