### ISSUE TITLE
Teamseite: Bilder

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#108]
Ich habe hier eine neue Mitarbeiterin erfasst und das Bild wird erneut nicht angepasst. Kannst du das bitte so fixe, dass es jetzt und auch in Zukunft immer gleich funktioniert?

Beispiel hier mit Selin Lehmann: https://abonax2023.visions.page/ueber-uns/team/

**Comment by christoph-menzi** [comment]
Ich kann den Fehler nicht reproduzieren. Wenn ich das Bild zuschneide, dann wird es auch im Frontend angezeigt.

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/8bee6a1b-bb68-406e-a0bd-9dc4566cdac3)

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/cabb785d-d97a-448f-b7bc-5dc94ea252e0)

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/bf34d2ac-088a-4c59-9e4f-1dec673acbf8)

**Comment by Riccardalina** [comment]
das bild ist viel grösser als alle anderen bitte schau es dir nochmals an im vergleich zu den anderen - ich hatte bereits schon einmal ein tickets erstellt wo ich darauf hingewiesen hatte, dass ich gerne einheitliche grössen hätte. das hattest du dann auch umgesetzt
