### ISSUE TITLE
Aktuelles

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#109]
Wieso wird diese Seite nicht angezeigt: https://abonax2023.visions.page/aktuelles/machbarkeitsstudie-fuer-pv-auf-kommunalen-gebaeuden.html

**Comment by christoph-menzi** [comment]
Ein kleines mieses fieses "Zeichen". Das zerstört den Contentaufbau. 

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/9c8dafd6-1919-40b2-973e-8fd5511fbdba)

Habe einen Workaroundlösung integriert nun funktioniert es wieder.
