### ISSUE TITLE
Footer: Design

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#11]
Im Footer haben wir noch ein paar Anzeigeprobleme bei den Spalten der Navigation:

<img width="1132" alt="Bildschirm­foto 2023-02-16 um 10 18 20" src="https://user-images.githubusercontent.com/85960512/219322128-c28e0313-640f-4ca7-b2e7-ae5d144b67b8.png">

Zudem wäre es gut, wenn das Logo etwas kleiner wäre.

Etwa so:
<img width="943" alt="Bildschirm­foto 2023-02-16 um 10 20 27" src="https://user-images.githubusercontent.com/85960512/219322411-6ec58c87-2bdb-46d2-81e9-fad0a0732f7f.png">

https://user-images.githubusercontent.com/85960512/219324675-8dbd5bdc-63af-4b7c-8729-d54d5b8d6072.mp4

**Comment by alexanderbuergin** [comment]
Social Media Navigation: Diese haben noch keinen Hover, diesen können wir auf das Grün des Brands setzen:

<img width="225" alt="Bildschirm­foto 2023-02-13 um 23 53 13" src="https://user-images.githubusercontent.com/85960512/219325154-d9c82006-768c-4890-b1fb-b79861eba4c1.png">

**Comment by alexanderbuergin** [comment]
Beim Footer wäre es gut, wenn dieser einen 2px border auf der oberen Seite bekommt, da wir die Situation haben, dass der Footer teilweise auf Elemente trifft welche dieselbe Hintergrundfarbe haben
`border-top: #fff solid 2px;`

<img width="1470" alt="Bildschirm­foto 2023-02-16 um 10 56 24" src="https://user-images.githubusercontent.com/85960512/219332105-c6403d20-b023-4890-bf04-f9541141397f.png">

<img width="1478" alt="Bildschirm­foto 2023-02-16 um 10 57 28" src="https://user-images.githubusercontent.com/85960512/219332471-7f72753e-d61f-4b08-8383-94b052ff9fb9.png">

**Comment by mguddelmoni** [comment]
Die Darstellung wie oben abgebildet kann ich nicht nachvollziehen. Bitte den browser Cache löschen oder die Seite im Inkognito Mode öffnen.

BorderTop ist gemacht, Logo kleiner, die Elemente sind im Grid.

<img width="1386" alt="Bildschirmfoto 2023-02-21 um 13 34 50" src="https://user-images.githubusercontent.com/64895942/220347910-8d7f98fe-1d3e-43dd-81cf-63d6af68aa30.png">
