### ISSUE TITLE
Aktuelles

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#110]
Wieso kann ich hier keinen inhalt hinzufügen?
https://abonax2023.visions.page/manager/?a=resource/update&id=39&reload=645df3e6d54137.13036551&class_key=modDocument&context_key=web

**Comment by christoph-menzi** [comment]
Das Template musste noch definiert werden. Habe es angepasst.

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/7b1dbbb1-14ee-4039-a6b3-9da02073206b)
