### ISSUE TITLE
Button richtig setzen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#111]
ich kriege den Link "Mehr" hier nicht richtig gesetzt, entweder ist er zu stark links ider zu stark in der mitte. was mache ich falsch. Auf der Startseite ist genau dasselbe dargestellt und es funktioniert.

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/f937818d-5c5b-43c1-8d2d-0e6cc3f58b0e)

Link: https://abonax2023.visions.page/angebot.html

**Comment by christoph-menzi** [comment]
Es gibt eine zusätzliche Einstellung, damit beim 2spaltigen Layout bei der Spalte Rechts auf der linken Seite ein Abstand generiert werden kann.

Ich habe Dir die Seite kurz angepasst. https://abonax2023.visions.page/manager/?a=resource/update&id=6

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/9623f587-1701-4cac-a3ea-59a33406bdea)
