### ISSUE TITLE
Falsches Datum im Event

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#112]
auf der Unterseite wird ein falsches Datum angezeigt, woher nimmt er das?

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/91dfdbea-6ee4-410e-b4e5-3f8bac5f6e38)

Link: https://abonax2023.visions.page/events/event-daten/abonax-bbq-2022-2.html

**Comment by Riccardalina** [comment]
Ausserdem wird auf derselben seite das bild immernoch unscharf angezeigt. Hatte ich schon einmal gemeldet.

**Comment by christoph-menzi** [comment]
Bild wird nun höher aufgelöst.

@mguddelmoni 
Datum stimmt eigentlich, aber im Frontend nicht.

Variable ist datumVon

{$_modx->resource.datumVon|date_format:"%d. %B %Y"}

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/3fc93c43-9a0b-4967-aa85-8078beb2880e)

**Comment by mguddelmoni** [comment]
Das Datum stimmt nun.

**Comment by Riccardalina** [comment]
danke dir! jetzt ist da nur noch ein komma anstatt eines punktes. Bitte Daten immer wiefolgt darstellen:
06. Juni 2023
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/09474cac-78af-49c4-8b78-65a17e575879)

**Comment by mguddelmoni** [comment]
Ist nun, mit dem Namen des Tages
Dienstag, 06. Juni 2023
