### ISSUE TITLE
Abstand Logo und Titel

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#113]
Könnte man bei diesem Element den Abstand zwischen Logo und Überschrift etwas vergrössern, damit es nicht mehr so aneinander klebt?

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/57384dde-3346-415b-95d9-4f67be3d52fc)

Beispiellink: https://abonax2023.visions.page/angebot/fachbereiche/energiewirtschaft.html

**Comment by mguddelmoni** [comment]
Kann eingestellt werden:
![Bildschirmfoto 2023-05-15 um 11 09 37](https://github.com/Riccardalina/Abonax-Website/assets/64895942/95361a72-3aab-4a00-a975-555e782da00f)

Habe es schon auf allen Fachbereichen angepasst.
