### ISSUE TITLE
Textanpassung Club

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#114]
Wo kann ich diesen Text im Club anpassen?

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/da44ac93-63a9-4ef0-be75-925b6b6b11e4)

**Comment by mguddelmoni** [comment]
Kann hier angepasst werden:
https://abonax2023.visions.page/manager/?a=resource/update&id=230&reload=6461f503a1fa89.35963958&class_key=modDocument&context_key=web
