### ISSUE TITLE
Titel Bewertungsübersicht Denkfabrik

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#115]
Der Titel hier ist unpassend, da es sich bei der Matrix um eine Übersicht von allen bewerteten Funktionen handelt.

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/ebbf64ca-1383-4676-be9c-f15452648a4e)

Eher so: So bewerten die Club-Mitglieder die abonax Innovationen

Link: https://abonax2023.visions.page/abonax-club/abonax-denkfabrik/

Ausserdem müssten wir hier noch festlegen wieviele Innovationen denn angezeigt werden? gibt es hier ein Maximum?

**Comment by mguddelmoni** [comment]
Der Text ist angepasst.
Es gibt kein Maximum. Nicht mehr relevante Innovationen können deaktiviert oder gelöscht werden im Backend.
