### ISSUE TITLE
Denkfabrik Bilder in Übersicht

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#116]
Die Bilder auf der Übersichtsseite werden nicht einheitlich angezeigt. man kann sie zwar croppen aber dargestellt werden sie wie sie ursprünglich hochgeladen wurden. Bitte so umbauen, dass sie immer gleich gross sind bzw. es einen voreingestellte crop funktion hat.

Link: https://abonax2023.visions.page/abonax-club/abonax-denkfabrik/

**Comment by mguddelmoni** [comment]
Habe zus. object-fit: cover eingestellt dass falls das Bild weniger hoch ist als der Artikel der Bereich trotzdem mit dem Bild gefüllt wird.
