### ISSUE TITLE
Link bei Bild in Logo Wall

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#117]
Ich würde auf dieser Seite gerne mehrere Logos hinzufügen von unseren Kunden und diese verlinken so dass die links sich in einem neuen fenster öffnen. gibt es dafür bereits ein element oder muss dafür was neues programmiert werden?

Link: https://abonax2023.visions.page/referenzen/logo-wall.html

**Comment by Riccardalina** [comment]
kannst du mir noch sagen welche masse das bild haben muss, damit es sich gut einpasst?

**Comment by mguddelmoni** [comment]
Es wird immer 100% Breit angezeigt. Ich denke im Verhältnis zwischen  1 : 1.5 (eschlikon logo) oder 1 : 1.6 (ibibi Logo)

also 400px x 600px oder 375px x 600px
