### ISSUE TITLE
Club: Vertical Align .nav-club

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#118]
Die Ausrichtung der Navigation Items ist sehr unschön. Die Ausrichtung könnte man so fixen:

`.nav-club .container .content ul li a {
    display: flex;
    align-items: center;
}`

---

Die `.nav-club` ist nicht scrollbar. Diese muss Scrollbar sein, wenn es eine Overflow hat.

<img width="425" alt="Bildschirm­foto 2023-05-19 um 22 33 07" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/972f9191-6fc7-4bb5-975c-413115fb8835">

---

Die Header Area ist sehr gross bemessen auf kleineren Screens, hier sollte man mit einem Query etwas in der Richtung machen:
`.nav-club .container .content ul {
    margin-top: 120px;
}`

---

Die .nav-club ist für kleinere Screens zu breit. 300+px sollte man erst nach 1800 px nutzen unter 1800 sollte man besser 280 nehmen.

---

Die Icons in der Sidenavigation sind sehr gross. 26px Breite reichen aus.

---

Die Ausrichtung des Logos und des Nav Buttons ist nicht harmonisch. Bitte on Baseline oder mittig ausrichten.

<img width="360" alt="Bildschirm­foto 2023-05-19 um 22 38 45" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/4aee4947-f1af-46f7-95df-02e0d1cbb827">

---

**Comment by alexanderbuergin** [comment]
Als Referenz: 

<img width="244" alt="Bildschirm­foto 2023-05-19 um 22 52 14" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/61ee4555-93b0-4fa9-9660-aa81d5fd6f8b">

Hier waren die Icons 20px – 26 könnte aber auch gut aussehen.

**Comment by mguddelmoni** [comment]
**ERLEDIGT**: Die .nav-club ist für kleinere Screens zu breit. 300+px sollte man erst nach 1800 px nutzen unter 1800 sollte man besser 280 nehmen.
**NEIN* Führt dazu dass die Untermenge nicht mehr richtig dargestellt werden.*: display: flex; align-items: center;
**ERLEDIGT**: Die .nav-club ist nicht scrollbar. Diese muss Scrollbar sein, wenn es eine Overflow hat.
**ERLEDIGT**: .nav-club .container .content ul { margin-top: 120px; }
**ERLEDIGT**: Die Icons in der Sidenavigation sind sehr gross. 26px Breite reichen aus.
**ERLEDIGT**: Die Ausrichtung des Logos und des Nav Buttons ist nicht harmonisch. Bitte on Baseline oder mittig ausrichten.
