### ISSUE TITLE
Club: Cards - Textgrösse ist sehr gross

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#120]
Die Textgrößen in den Cards sind etwas unleserlich, kann man die grössen der einzelnen Typoelemente Relational im Club innerhalb der Cards verkleinern?

<img width="1253" alt="Bildschirm­foto 2023-05-19 um 22 45 05" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/b9d8fbfb-3e98-43b5-bf14-028fb1a664da">

**Comment by mguddelmoni** [comment]
Grösse ist angepasst (Gab bereits ein anderes issue zu diesem Thema)
Die Schriftgrässe ändert sich in 3 Breakpoints
