### ISSUE TITLE
Club: Bodyspace

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#121]
Im Club bitte den Bodyspace zu allen Seiten (Seitenrändern) gleich einstellen:

<img width="1471" alt="Bildschirm­foto 2023-05-19 um 22 47 19" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/ccc8d663-f12f-47b8-9045-acac14e9f86a">

---

Dieser Space sollte vor allem auf kleineren Bildschirmen kleiner und nicht grösser werden.

Hier reichen etwa 30px

<img width="599" alt="Bildschirm­foto 2023-05-19 um 22 48 43" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/8dd06ed8-9dc9-4a16-86e0-0e6deac1b632">

**Comment by mguddelmoni** [comment]
Responsive Breakpoints und container optimiert
