### ISSUE TITLE
Club: Artikel

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#122]
So funktioniert die Ansicht leider nicht:

<img width="1255" alt="Bildschirm­foto 2023-05-19 um 22 50 19" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/fc27f5d5-70aa-4516-900c-6a99e65dc7a6">

---

Z-index für den Button:

<img width="506" alt="Bildschirm­foto 2023-05-19 um 22 50 57" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/ab57708a-55bc-4f42-b680-89add98b425f">

**Comment by alexanderbuergin** [comment]
Mobile sieht der Artikel extrem verrissen aus. Seitenabstände auf 30 px anpassen und die Schriften verkleinern. Button in der unteren ecke.

<img width="402" alt="Bildschirm­foto 2023-05-19 um 22 53 53" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/b002194b-d934-401b-b747-d9983f3a7dd2">

**Comment by mguddelmoni** [comment]
Die Inhalte wurden von der alten Seite kopiert.
Bildmaterial bitte passend zum Layout auswählen.

Bitte HTML bereinigen.
Kann man hier machen: https://www.htmlwasher.com/ 

Habe das HTML von https://abonax.ch/abonax-club/abonax-denkfabrik/test2.html  bereits bereinigt als Beispiel.

**Comment by Riccardalina** [comment]
Das funktioniert jetzt grundsätzlich so aber die Bilder werden in der Mobileansicht nicht verkleinert. Woran liegt das?

**Comment by mguddelmoni** [comment]
Da sind noch ein figure und image tags drin die mit styles definiert wurde:

figure style="width: 497px; max-width: 497px;"...
image style="width: 497px; max-width: 497px; height: 321px;"....

Als Beispiel hier Bereinigt: https://www.abonax.ch/abonax-club/abonax-denkfabrik/emil-die-alternative-zu-ecarup.html
