### ISSUE TITLE
Club: Dashboard

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#123]
Die Icons sind viel zu gross, der Pfeil verschwindet und die Abstände sind auch zu gross.
Die Schrift ist so auch sehr unpassend

<img width="699" alt="Bildschirm­foto 2023-05-19 um 22 56 34" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/6b415b2f-3d8a-42f5-886d-6efc92723002">

**Comment by mguddelmoni** [comment]
hat nun optimierte Schriftgrössen und paddings
