### ISSUE TITLE
Club: Dashboard

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#124]
Der Haupttitel ist unverhältniss mässig gross

<img width="756" alt="Bildschirm­foto 2023-05-19 um 22 56 37" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/a6fc90e2-b2aa-4fe6-b7c5-8378a33482c8">

**Comment by alexanderbuergin** [comment]
Aus Mobile sieht man fast nur weiss.

<img width="406" alt="Bildschirm­foto 2023-05-19 um 23 02 25" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/6dc10327-0015-4a4d-af16-6f9d2c797e17">

**Comment by mguddelmoni** [comment]
Breite angepasst, Heading auf H3 gesetzt
