### ISSUE TITLE
Club: Cashboard Sidebar

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#125]
Hier stimmen die Ausrichtungen und Verhältnisse nicht

<img width="357" alt="Bildschirm­foto 2023-05-19 um 22 56 41" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/09126102-480b-4476-82f3-cb6e0131dc30">

**Comment by alexanderbuergin** [comment]
<img width="251" alt="Bildschirm­foto 2023-05-19 um 22 59 11" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/f04a5b4b-ea77-4109-9adb-0e594b79da54">

**Comment by mguddelmoni** [comment]
Bite Cache leeren. Kann ich nicht bestätigen, siehe Screenshot (Mac Safari, Crome, FF)

![Uploading Bildschirmfoto 2023-05-23 um 15.59.18.png…]()

**Comment by alexanderbuergin** [comment]
Ich kann keine Veränderung feststellen


<img width="1507" alt="Bildschirm­foto 2023-05-23 um 16 20 48" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/6e72e705-6d2d-4a87-bf9c-f4830983148c">


Chrome: 113.0.5672.126

**Comment by alexanderbuergin** [comment]
Zwischen 400 und 1500px Bildschirmgrösse
