### ISSUE TITLE
Club: Profiel

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#126]
Weil weise hat es sichtbare Fehlermeldungen teilweise sind diese nicht wirklich als Fehler erkennbar.

<img width="749" alt="Bildschirm­foto 2023-05-19 um 23 00 11" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/d639aa37-66ba-4020-ad4d-2c12849b914c">

**Comment by alexanderbuergin** [comment]
Auf kleineren Bildschirmen die Person über das Formular heben, erst bei grossen Bildschirmen kann man die Spalten so machen.

<img width="1052" alt="Bildschirm­foto 2023-05-19 um 23 01 01" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/1dcd5a57-a811-49d8-a40c-572db1255775">

**Comment by mguddelmoni** [comment]
Das ist so: Wechsel der Ansicht bei 980px.
Bei Fehler wird nun auf das entsprechende Formular gescrollt.

**Comment by alexanderbuergin** [comment]
In dem Fall musst du den Breakpoint auf 1400px stellen, so wie es aktuell ist, ist es nicht akzeptabel.

**Comment by alexanderbuergin** [comment]
<img width="1206" alt="Bildschirm­foto 2023-05-23 um 16 18 52" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/c70aa487-0079-4e0e-90b9-dc2bf8119e19">

**Comment by Riccardalina** [comment]
Wurde das erledigt?

**Comment by mguddelmoni** [comment]
Das wurde erledigt. Das Ticket wurde ja geschlossen
