### ISSUE TITLE
Topbar / Navigation: Design

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#13]
Die Abstände wie auch die Logo-Grösse sind noch etwas unharmonisch:

<img width="1396" alt="Bildschirm­foto 2023-02-13 um 23 54 03" src="https://user-images.githubusercontent.com/85960512/219328047-e17f4a0f-d934-4b14-911e-e744faf2df49.png">

Desktop Navigation:In Video gehe ich auf noch ein paar Details mehr ein:
https://user-images.githubusercontent.com/85960512/219329832-16eaf4a9-659c-42e6-910d-371bed37ed01.mp4

Mobile Navigation:
https://user-images.githubusercontent.com/85960512/219331216-a2206ad8-3265-463f-9874-95ba78759ede.mp4

Hexa Code Linie: `#1e193d`

**Comment by Riccardalina** [comment]
@mguddelmoni: In diesem Video gibt es noch einige Punkte, die auf der Website nicht angepasst wurden. Bitte nochmals prüfen ob alles erledigt wurde, was Alexander im Video erwähnt.

Mobile Navigation:
https://user-images.githubusercontent.com/85960512/219331216-a2206ad8-3265-463f-9874-95ba78759ede.mp4

**Comment by mguddelmoni** [comment]
Habe mir das Video nochmals durchgesehen und angepasst was ich gefunden habe.
Bitte in Zukunft keine Videos. Das repetitive Durchschauen erfordert sehr viel Zeit.
