### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#131]
Der Kopf von jedem Mitarbeiter wird hier immer abgeschnitten. Könnt ihr den Zuschnitt bitte so anpassen, dass das nicht passiert?
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/034f5a3b-eac1-405d-96da-4bee55a0a9ef)

Ausserdem verstehe ich nicht ganz woher er hier diesen Event nimmt:
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/eaa04c71-8231-4526-8e1c-000992d29454)

Link: https://abonax2023.visions.page/newslettervorlagen/newsletter2.html

**Comment by mguddelmoni** [comment]
Man kann auswählen aus welchem Bereich die Events geholt werden:

![Bildschirmfoto 2023-05-22 um 12 34 27](https://github.com/Riccardalina/Abonax-Website/assets/64895942/a229975e-14e7-4d72-ae80-5b8938eb9d99)

Habe den Filter noch optimiert (Falls Mehrfachauswahl) und die Sortierung angepasst (Datum aufsteigend).

**Comment by Riccardalina** [comment]
der Abstand hier müsste noch gefixt werden:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/38f56561-fef6-4654-9ea8-95abb44165ea)

**Comment by mguddelmoni** [comment]
Ist nach erneutem Speichern nun weg (Cache)
