### ISSUE TITLE
Newsletter Bilder

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#134]
Hier sind die Bilder noch verzerrt nach dem Testversand:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/cc338613-db24-4de0-906f-a87320e81993)

**Comment by mguddelmoni** [comment]
Das ist behoben.
Getestet auf:
- Mac Mail
- Mac Outlook
- Windows Outlook365
- Exchange
