### ISSUE TITLE
Header Bild Artikel Aktuelles

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#136]
Das mit den Bildern ist noch nicht zufriedenstellend gelöst. Haben wir da andere Optionen, die die Bilder nicht zu verziehen oder komisch darstellen wie bei den derzeitigen Beispielen unter Aktuelles?

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/203a4394-278e-4003-ae21-485e4d9f1c75)

**Comment by mguddelmoni** [comment]
Das Bild ist nicht verzogen. Bitte erstellt unds doch ein Layout dass der Anforderung von einem "Bild mit Text" entspricht.
ebenfalls ist das Bild mit 960px zu klein für hochauflösende Bildschirme.

**Comment by Riccardalina** [comment]
Hättet ihr denn eine Idee wir wir das mit solchen Bildern anders umsetzen könnten? Beispielsweise, dass man die Möglichkeit hat Thumbnail Bild und Header Bild auf der Detailseite individuell auszuwählen?

**Comment by mguddelmoni** [comment]
Es gibt nun ein zweites, **optionales** Bild für die Detailseite der Artikel:
Siehe https://www.abonax.ch/aktuelles/neues-clubmitglied-technische-gemeindebetriebe-bischofszell.html

Diese Bilder müssen noch hinterlegt werden.
