### ISSUE TITLE
Profilbild Clubbereich

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#138]
Bei den Profilen werden die Bilder teils nicht angezeigt, woran könnte das liegen?
![MicrosoftTeams-image (2)](https://github.com/Riccardalina/Abonax-Website/assets/122005698/12a5116e-fb56-4718-bf4c-f97a3ac152e4)
![MicrosoftTeams-image (6)](https://github.com/Riccardalina/Abonax-Website/assets/122005698/1ec389f9-dd01-4bea-9cad-b85355601a10)
![MicrosoftTeams-image (7)](https://github.com/Riccardalina/Abonax-Website/assets/122005698/0494dd14-3906-4093-be01-b6005298a3e5)

**Comment by mguddelmoni** [comment]
Bild wurde beim Import nicht zugewiesen. Daher wurde beim Speichern das Standardbild entfernt.

**Comment by Riccardalina** [comment]
Wie meinst du das genau? Was haben wir falsch gemacht?

**Comment by mguddelmoni** [comment]
Ihr habt nichts falsch gemacht. Das Problem wurde behoben.
