### ISSUE TITLE
Section Spacing: Nicht identisch

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#14]
An einigen Stellen passt das Spacing zwischen den einzelnen Sectionen nicht ganz:
https://user-images.githubusercontent.com/85960512/219334674-49d7a9b2-c221-4a56-b8eb-51315a3af978.mp4

Auf dieser Seite haben wir eine ähnliche Situation:
https://abonax2023.visions.page/referenzen

<img width="1474" alt="Bildschirm­foto 2023-02-16 um 11 06 39" src="https://user-images.githubusercontent.com/85960512/219334526-81322957-1511-48c4-8478-461ad627b20a.png">

**Comment by mguddelmoni** [comment]
Habe den Cluttersize auf 2 rem erhöht. Nun sollte generell mehr spacing sein zwischen den Elementen.
