### ISSUE TITLE
Navigationsbalken auf kleineren Bildschirmen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#140]
Der Balken klebt oben und hat keinen Abstand wie sonst auf grösseren Bildschirmen. Sollte das so sein?

<img width="953" alt="image" src="https://github.com/Riccardalina/Abonax-Website/assets/122005698/d41927a5-bbe3-43cb-985a-335df148c769">

**Comment by mguddelmoni** [comment]
Das ist so gewollt bei Tablet-Grösse
