### ISSUE TITLE
Links Bild Rechts Text

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#143]
Auf mittleren Bildschirmen Sicht dies nicht sehr harmonisch aus. Das Bild sollte die ganze Breite einnehmen.

Zudem würde es reichen, wenn der Breakpoint auf kleinere Bildschirme gesetzt würde.

<img width="943" alt="Bildschirm­foto 2023-05-25 um 00 21 52" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/88bf8b0a-fc13-4a20-a934-c9579198bf11">

**Comment by mguddelmoni** [comment]
Ist Inhalt:
Kann in den Layouteinstellungen des 2 Spaltes eingestellt werden.
Erledigt

![Bildschirmfoto 2023-07-10 um 13 55 38](https://github.com/Riccardalina/Abonax-Website/assets/64895942/4ba63cbf-9c78-4a77-bbd5-d5598b84ccd1)

**Comment by Riccardalina** [comment]
Hier dasselbe bzgl. Anleitung. Ich weiss nicht bei welchen Elementen ich welche Spaltenbreiten für welche Bildschirme benötige. Dafür bitte eine Anleitung erstellen, damit wir diese Probleme in ZUkunft nicht mehr haben.
