### ISSUE TITLE
Club Denkfabrik: Kommentare

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#149]
Wo kann ich diese Kommentare verwalten und löschen:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/92b9ffcd-5914-48a1-9708-c9ea02afe982)

**Comment by mguddelmoni** [comment]
Jeweils unter Template-Variabeln >> Kommentare bei dein einzelnen Einträgen
![Uploading Bildschirmfoto 2023-05-25 um 17.52.46.png…]()
