### ISSUE TITLE
Container / Wrapper Spacing

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#15]
Das Spacing gegen den Display-Rand ist nicht an allen Stellen identisch, hier wäre eine Harmonisierung schön:

https://user-images.githubusercontent.com/85960512/219336366-8c895e63-87a1-4a8f-84f9-84023c7551a0.mp4

**Comment by alexanderbuergin** [comment]
<img width="399" alt="Bildschirm­foto 2023-02-16 um 11 16 17" src="https://user-images.githubusercontent.com/85960512/219336894-e029828a-5ae0-4a39-af7b-b3628c2c0561.png">

**Comment by mguddelmoni** [comment]
Logo wird nun an Container ausgerichtet. MartinRight von Hamburger ist nun konform mit clutterSize 2rem
