### ISSUE TITLE
Mail Passwort zurücksetzen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#151]
Diesen Text müsste man in Du-Form schreiben. Kann ich das selbst anpassen? Wenn ja wo?
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/3c6f9ff9-d5a9-4fcd-b7dc-2b7699022251)

**Comment by mguddelmoni** [comment]
Das kann nicht selbst bearbeitet werden.
Habe es angepasst.
