### ISSUE TITLE
Clubbereich Logindaten Mail

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#154]
Dieses Mail ist noch auf englisch.

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/2e938c84-a548-42a8-913c-a3d71154809a)

**Comment by mguddelmoni** [comment]
@Riccardalina Von wo aus hast du diese Mail ausgelöst? Vom frontend oder vom Backend?

**Comment by Riccardalina** [comment]
vom frontend wenn ich mein passwort zurücksetzen wollte

**Comment by Riccardalina** [comment]
Ich habe das ebenfalls erneut an christoph per mail gemeldet da es dringend ist. Der Inhalt und auch der Link sollte wiefolgt angepasst werden: 

Hallo «Vorname » (nicht wie bis anhin die Mailadresse),

Hier sind Deine Logindaten für den abonax Clubbereich:

Benutzername:
Passwort:

Sobald Du Dich im Clubbereich unter www.abonax.ch/club angemeldet hast, kannst Du Dein Passwort ändern.

Liebe Grüsse
Dein abonax Team
