### ISSUE TITLE
Aktuelles im Footer

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#156]
Wie kann ich diese Zahlen hier steuern:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/94fd8bb2-d7c1-413e-b3fc-4f043e1aaf21)

**Comment by mguddelmoni** [comment]
Diese Zahlen werden auch die real erfassten und veröffentlichten Artikel in der jeweiligen Rubrik gesteuert. 

Karriere > Jobs
Aktuelles

10 Aktuelles 
0  Jobs

**Comment by Riccardalina** [comment]
ok aber ich möchte ja nicht, dass da immer alle artikel bei aktuelles angezeigt werden - nur die neusten - kann ich das irgendwie steuern indem ich die neusten artikel markiere?
