### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#159]
Linie steht oben über und unten ist sie zu kurz.

Wahrscheinlich ist die verschoben positioniert.

<img width="944" alt="Bildschirm­foto 2023-06-01 um 17 01 04" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/c2b6c477-4da0-4657-9d4e-ad23e1e0c952">

**Comment by mguddelmoni** [comment]
Erledigt.
Anmerkung:: Im Layout hat sie vor den Elementen angefangen.
