### ISSUE TITLE
Offer Links

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#160]
- [x] Aus kleineren Bildschirmen kleben die Items am Seitenrand, diese sollten das normale Spacing haben.
- [x] Bitte die Pfeil-Icons auf Mobile kleiner
- [x] Bitte die Pfeil-Icons in Dunkelblau

<img width="598" alt="Bildschirm­foto 2023-06-01 um 16 55 39" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/14f60d36-94c3-41a5-a956-65024cfef9d3">

**Comment by Riccardalina** [comment]
Mir scheint dieses grün etwas dunkler als unser Logogrün? Muss das so sein @alexanderbuergin oder sollte das nicht etwas heller sein?
