### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#162]
Der Avatar funktioniert immer noch nicht:

<img width="385" alt="Bildschirm­foto 2023-06-02 um 13 31 14" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/658c6394-eda5-4c95-9fe7-1fa2ac59b264">

**Comment by mguddelmoni** [comment]
Bei Alexander Bürgin ist kein Bild hinterlegt. Dies sit das Standfartbild dass geladen wird wenn keines hinterlegt wurde vom Kunden

**Comment by mguddelmoni** [comment]
![Bildschirmfoto 2023-07-10 um 11 10 24](https://github.com/Riccardalina/Abonax-Website/assets/64895942/2e7e1e0a-dd45-4a48-acaf-87edf1531237)

**Comment by alexanderbuergin** [comment]
@mguddelmoni Das ist nicht, was ich meinte.

Der Text sollte eigentlich neben dem Bild sein, wenn das nicht geht, sollte das Bild mindestens zensiert sein und einen kleinen Abstand zwischen dem Bild und dem Namen.

**Comment by Riccardalina** [comment]
Bitte nochmals aufnehmen und umsetzen

**Comment by mguddelmoni** [comment]
Das lässt sich so nicht steuern, da die Länge des namens unbekannt ist und somit jeder name individuell umbricht.
Ich schlage vor dieses element generell zu zentrieren, das sieht allemal besser aus.
![Bildschirmfoto 2023-07-11 um 11 53 12](https://github.com/Riccardalina/Abonax-Website/assets/64895942/465e54fb-8ecb-422f-a001-bdd393bde002)

**Comment by Riccardalina** [comment]
Dann bitte zentrieren und einen etwas grösseren Abstand zwischen Bild und Namen machen. So klebt es ein wenig fest aneinander.
