### ISSUE TITLE
Feed News Radar

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#163]
Hier bitte die Titel und den Text etwas kleiner machen, so ist es sehr unübersichtlich.

<img width="1067" alt="Bildschirm­foto 2023-06-02 um 13 32 42" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/5483889b-05b0-4186-849f-d07728e03001">

@Riccardalina Ich fände es gut, wenn der Teaser Text (Lauftext) auf 160 bis 200 Zeichen gekürzt werden würde – automatisch. Was meinst du? Wenn der Text länger als 160 bis 200 Zeichen ist, würde ein ... an den Inhalt angehängt werden.

**Comment by Riccardalina** [comment]
Ja bin der selben Meinung. Bitte so umsetzen.
