### ISSUE TITLE
News Artikel: Club

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#164]
Der Header ist sehr unübersichtlich

https://abonax.ch/abonax-club/news-radar/ebl-und-raurica-wald-ag-setzen-auf-nachhaltige-und-regionale-energieversorgung-mit-neuem-e-lkw.html

<img width="1120" alt="Bildschirm­foto 2023-06-02 um 13 36 06" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/511a7a70-1503-4db2-9660-6082e6c8a29e">

- [ ] Bitte Titel kleiner
- [ ] Weniger Abstand Links und Rechts (auf kleineren Bildschirmen – unter 1800px)

**Comment by mguddelmoni** [comment]
Kann im Inhalt eingestellt werden (Screenshot)

![Bildschirmfoto 2023-07-10 um 11 07 41](https://github.com/Riccardalina/Abonax-Website/assets/64895942/a4b86d4b-9633-4f62-8498-64ea1c6d93dd)

**Comment by alexanderbuergin** [comment]
Der Titel eine Artikels sollte immer eine H1 sein. Hier haben wir es mit einem Styling und nicht mit einem Tagging Problem zu tun.

**Comment by Riccardalina** [comment]
wurde das fertig umgesetzt?

**Comment by mguddelmoni** [comment]
_Der Titel eine Artikels sollte immer eine H1 sein. Hier haben wir es mit einem Styling und nicht mit einem Tagging Problem zu tun._

Das ist so, kann auch so definiert werden.

>> Der Titel der Seite kann auf H1 gesetzt werden, die Grösse aber auf die von H4 gesetzt werden.

- Heading = Überschrift (h1,h2,h3,....)
- Anzeigegrösse = CSS Auszeichnung, überschreibt Anzeigegrösse des Headings

Im Screenshot: Heading H1 mit Formatierung von H4

_wurde das fertig umgesetzt?_

>> Das ist Inhalt und kann beim Anlegen oder beim Bearbeiten eines Artikels definiert werden.
