### ISSUE TITLE
Newsletter: Titel abgeschnitten

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#165]
Titel werden in den Newslettern teilweise abgeschnitten: 
![MicrosoftTeams-image (8)](https://github.com/Riccardalina/Abonax-Website/assets/122005698/60e253e4-9328-406a-94fc-1a2f4c2e5920)

**Comment by mguddelmoni** [comment]
Ich kann diesen Newsletter nirgends mehr finden, also kann ich dieses Issue nicht analysieren.
"Erneuerbarenrichtlinie" scheint aber ein sehr langes, falsch geschriebenes Wort zu sein.
