### ISSUE TITLE
Eigene Formulare erstellen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#166]
Ich hätte gerne die Möglichkeit eigene Formulare für Events zu erstellen. Haben wir dafür eine Funktion?

**Comment by mguddelmoni** [comment]
Wir werden Formalicious installieren

**Comment by mguddelmoni** [comment]
Das Modul ist installiert und konfiguriert.

1. Formular erstellen https://abonax.ch/manager/?a=home&namespace=formalicious 
2. Formular mit dem Contenblock Element einfügen und auswählen https://abonax.ch/manager/?a=resource/update&id=291
3. Vorschau des Formulars https://abonax.ch/formulartest.html
