### ISSUE TITLE
Call to action

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#170]
Der Call to Action müsste breiter sein

<img width="1155" alt="Bildschirmfoto 2023-07-06 um 12 03 32" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/8bdceed0-accb-4831-97e7-8f07ae82a9a4">

**Comment by mguddelmoni** [comment]
![Bildschirmfoto 2023-07-10 um 10 33 02](https://github.com/Riccardalina/Abonax-Website/assets/64895942/b585adcf-8687-4164-806a-ea9d7e8ac493)
Das 2 Später Layout nmuss entsprechend eingestellt werden für das Call To action 6/12 reicht nicht. Siehe Screenshot

**Comment by alexanderbuergin** [comment]
@Riccardalina: Die Anpassung musst du machen.

**Comment by Riccardalina** [comment]
Gibt es irgendein Handbuch oder eine Vorlage dafür wann ich welche Einstellungen für welche Elemente hier machen muss? Wenn nichgt wäre ich froh, wenn ihr mir da etwas erstellen könntet. ich habe leider keine Info und deshalb auch keinen Überblick diesbezüglich..
