### ISSUE TITLE
Archivfunktion Aktuelles

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#173]
Wir benötigen noch eine Archivfunktion, damit alte Artikel zugewiesen und geordnet werden können.

**Comment by mguddelmoni** [comment]
Ich habe eine Pagination eingefügt ab 15 Artikeln wird diese unten angezeigt.

**Comment by Riccardalina** [comment]
hi mirko, das funktioniert grundsätzlich. jetzt haben wir aber noch das problem, dass im footer immernoch 23 artikel als "neu" deklariert werden. wie kann ich das steuern? 
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/dadfb27a-f3c7-4761-8d2b-3ae2ff950b85)

**Comment by Riccardalina** [comment]
@mguddelmoni Bitte um Feedback dazu

**Comment by christoph-menzi** [comment]
Wenn ich den Code richtig interpretiere werden einfach die Kind-Elemente gezählt.

Was ist den "Neu" und was ist nicht mehr "Neu"?

**Comment by Riccardalina** [comment]
Was meinst du mit Kind Elemente? Ich sollte selbst steuern können welche Artikel neu sind und unten in der Zahl angezeigt werden. Geht das? Welche neu sind und welche nicht, ändert sich monatlich.

**Comment by christoph-menzi** [comment]
Eine manuelle Zuweisung wäre sicherlich möglich. 

Dann gibt es neu eine Einstellung pro Dokument z.B. via Dropdown Neu ja/nein
Danach würden wir alle Elemente durchsuchen nach "Neu = ja" und eine Funktion programmieren der diese Elemente filtert und zusammenzählt.
Sinnvollerweise gibt es dann eine nicht veröffentlichte Seite, wo Du alle Dokumente mit Neu = ja anzeigen lassen kannst.

Ich würde mal 1-2h Aufwand schätzen um dies so umzubauen. Ich muss das testen.

Wird das nur im Footer mit "Neu" angezeigt? Gibt es weitere Seite wo dies auch angezeigt wird?

**Comment by Riccardalina** [comment]
das klingt doch gut, kannst du gerne so umsetzen. Nein die Info wird nur im Footer angezeigt, nirdgens sonst.

**Comment by mguddelmoni** [comment]
Das Feld Highlighted gibt es schon.
Habe die Anzahl angepasst im Footer. Es zählt nun nur noch die "Hervorgehobenen" Beiträge.

![Bildschirmfoto 2024-02-22 um 11 09 07](https://github.com/Riccardalina/Abonax-Website/assets/64895942/22923aea-f4d3-46e3-a8d3-4a0cd163aee6)
