### ISSUE TITLE
Bewertungen Denkfabrik

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#174]
Die Bewertungsübersicht wird komisch dargestellt. Ein Punkt ist ausserhalb der Matrix und die Erklärungen wenn man darüber hoovert sind nicht lesbar da ebenfalls ausserhalb des Seitenrandes.

![2023-07-13 15 52 41](https://github.com/Riccardalina/Abonax-Website/assets/122005698/9f76ec23-2d66-406f-a5ab-5b2c64bf65d5)

**Comment by Riccardalina** [comment]
Wenn man über die Quadrate hoovert ist der Text immernoch abgeschnitten
![2023-07-17 10 09 36](https://github.com/Riccardalina/Abonax-Website/assets/122005698/09038204-157d-458c-a719-13fe095e307b)

**Comment by mguddelmoni** [comment]
Bitte Cache leeren:

![Bildschirmfoto 2023-07-17 um 11 05 03](https://github.com/Riccardalina/Abonax-Website/assets/64895942/df00114d-8622-45cd-9b86-8feb554f089a)
