### ISSUE TITLE
Textumbruch Zwischengrösse Event

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#178]
Dieser Textumbruch "bis 17.00 Uhr" sollte auf der gleichen Höhe wie die Zeile oben beginnen:
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/40087e28-361f-4a4e-b4e8-b167381c0de2)

Bitte auf allen Bildschirmgrössen anpassen

**Comment by mguddelmoni** [comment]
Da es sich um Fliesstext Darstellung handelt kann ich nur den Umbruch als ganzes erzwingen.
Ich habe keine Kontrolle über die Länge des Textes. 

So sollte es aber einigermassen gut aussehen:

![Bildschirmfoto 2023-08-03 um 14 09 14](https://github.com/Riccardalina/Abonax-Website/assets/64895942/d3b80650-bd5b-4467-85c2-22dbc46a7c31)

**Comment by mguddelmoni** [comment]
![Bildschirmfoto 2023-08-03 um 14 11 59](https://github.com/Riccardalina/Abonax-Website/assets/64895942/0156f8bc-69f9-47bf-a223-c9924e850515)

**Comment by Riccardalina** [comment]
Es handelt sich hier um die Unterseite des Events und diese Angaben sind eigentlich kein fliesstext.. bitte nochmals anschauen.

<img width="416" alt="image" src="https://github.com/Riccardalina/Abonax-Website/assets/122005698/14302c6f-f52e-4026-bab5-d2214fc85b87">


Link: https://abonax.ch/events/event-daten/abonax-energie-forum-iii.html

**Comment by mguddelmoni** [comment]
Danke für den Link. Das war an anderer Stelle. Ich habe die Anpassungen un auch hier angewendet.
