### ISSUE TITLE
Social Media: Navigation

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#18]
Social Media Navigation: Diese haben noch keinen Hover, diesen können wir auf das Grün des Brands setzen:

Die Button/Social Media Navigation hat auch noch eine Verlinkungen.

@Riccardalina: Welche Seiten wollt ihr hier verlinken?

<img width="225" alt="219325154-d9c82006-768c-4890-b1fb-b79861eba4c1" src="https://user-images.githubusercontent.com/85960512/219339289-415b6f2d-2933-4afa-93ae-2d3f2776ed37.png">

**Comment by Riccardalina** [comment]
wir würden hier Linkedin und Youtube verlinken:

Link Youtube: https://www.youtube.com/@abonaxag991/
Link Linkedin: https://www.linkedin.com/company/3844408/

**Comment by mguddelmoni** [comment]
Hover ist gesetzt und Icons verlinkt
