### ISSUE TITLE
Footer Navigation Mobil

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#180]
Das sieht etwas unstimmig aus:

<img width="473" alt="Bildschirm­foto 2023-07-21 um 00 03 22" src="https://github.com/Riccardalina/Abonax-Website/assets/85960512/8147978c-f720-49cd-830f-7fbe8a5dab39">

**Comment by mguddelmoni** [comment]
Den Abstand des ersten Unterelements habe ich nun ein wenig verringert.
Ansonsten bitte immer eine präzise Handlungsanweisung was genau angepasst werden muss.
