### ISSUE TITLE
Testimonial Elemente

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#181]
Wir haben 3 verschiedene Testimonial Elemente bei welchen die Bilder nicht quadratisch sind und das Anführungszeichen etwas grösser ist als auf der Vorlage. 

Beispiellink: https://www.abonax.ch/referenzen/projekte/online-verfuegbarkeits-check-fuer-fernwaerme.html

Aktuelle Vorschau:
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/73f5743c-fbc9-49c8-b178-d991d68335a5)

Vorlage:
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/fc9e7432-f9b4-4b81-b80a-540ede7c48c7)

**Comment by Riccardalina** [comment]
Das eine Bild ist quadratisch, das andere nicht:

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/7b4c90e8-495e-4ee5-9e02-4ac22e154ac3)

**Comment by Riccardalina** [comment]
@mguddelmoni jetzt überlappen die Inhalte: 
<img width="554" alt="image" src="https://github.com/Riccardalina/Abonax-Website/assets/122005698/5e365501-788a-44f0-87a6-165fd11bab97">


Wir würden den Bericht gerne baldmöglichst veröffentlichen, könntet ihr das bitte finalisieren?

**Comment by mguddelmoni** [comment]
Kann ich nicht bestätigen Siehe Video.
Bitte Cache leeren.

https://github.com/Riccardalina/Abonax-Website/assets/64895942/ef03f1db-c307-4b75-9f39-f9f8a11708f4

**Comment by Riccardalina** [comment]
bei mir ist es überlappend auf google chrome und edge - auch nach löschen des caches. wahrscheinlich ist mein bildschirm grösser - wenn du das fenster weiter in die breite ziehst, überlappt es auf einmal

**Comment by mguddelmoni** [comment]
Okay. Habs gesehen und gefixt. Danke fürs Feedback
