### ISSUE TITLE
Bildqualität CTA

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#182]
Die Bildqualität bei diesem CTA ist nicht gut:
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/2a596ab0-0741-418a-b757-d56151c62166)

Link: https://www.abonax.ch/referenzen/projekte/online-verfuegbarkeits-check-fuer-fernwaerme.html
(Nicht veröffentlichte Seite)

**Comment by mguddelmoni** [comment]
Das Original an sich ist schon relativ unscharf.
Habe die Ausgabegrösse verdoppelt, ist etwas besser, aber das mach das unscharfe Original nicht wett.
Besser das Bild auswechseln.

**Comment by Riccardalina** [comment]
Das Bild hat 300dpi - die qualität sollte also eigentlich ausreichen.. ist vielleicht beim Upload etwas schiefgelaufen?

**Comment by mguddelmoni** [comment]
Die 300 DPI nützen nichts wenn das Bild in dieser Grösse schon unscharf ist.
Kannst du vielleicht das Bild nochmals hochladen oder mir zusenden?

**Comment by Riccardalina** [comment]
![AbonaxAG_feb22__59-website](https://github.com/Riccardalina/Abonax-Website/assets/122005698/c11cf884-d6ea-435c-877c-5d88ed374005)

**Comment by mguddelmoni** [comment]
Das Bild verwendet einen nicht vom Web unterstützten Farbraum. Dieser wird automatisch konvertiert. Das Bild hat die gleiche Schärfe, aber ein etwas abweichende Farben.  (Anstatt RGB sRGB oder Adobe RGB?)

![Bildschirmfoto 2023-08-07 um 12 56 36](https://github.com/Riccardalina/Abonax-Website/assets/64895942/4a20cfa1-8683-4d48-a94a-941fb6c30b93)
