### ISSUE TITLE
CTA Element

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#183]
Dieser CTA sieht auf kleineren Bildschirmen nicht gut aus. Liegt das immernoch an falschen Einstellungen oder woran sonst? falls ja, dann brauche ich das handbuch damit ich das verhindern kann.

<img width="587" alt="image" src="https://github.com/Riccardalina/Abonax-Website/assets/122005698/9384d1a7-8036-4c29-b852-c6b9eceae761">

Link: https://www.abonax.ch/referenzen/projekte/online-verfuegbarkeits-check-fuer-fernwaerme.html

**Comment by mguddelmoni** [comment]
Das CTA habe ich nun angepasst. Der Inhalt sollte den Rahmen nun auf allen Bildschirmen nicht mehr verlassen
