### ISSUE TITLE
Dokument in neuem Fenster öffnen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#185]
Bei der Stellenausschreibung unter "Stellenausschreibugn herunterladen" habe ich ein Dokument angehängt. Ich kann im Element aber nirgends anwählen, dass sich das Dokument beim Download in einem neuen Fenster öffnen soll. Bitte diese Funktion hinzufügen. Diese Möglichkeit sollte bei allen Elementen die Dokument Downloads oder Links haben bestehen.

Link: https://www.abonax.ch/ueber-uns/jobs/projektentwicklerin-abonax-club.html

**Comment by mguddelmoni** [comment]
Bei den Dokument Downloads können nur Dokumente ausgewählt werden. Entsprechend habe ich es so eingerichtet dass alle Dokumente in einem neuen Fenster geöffnet werden.

Normale Links müssen im normalen Richtext Editor erfasst werden.
