### ISSUE TITLE
Titel Job

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#186]
Titel geht über den Rand:
<img width="635" alt="image" src="https://github.com/Riccardalina/Abonax-Website/assets/122005698/10a1925e-ed44-4242-a5ff-68f0e39105ec">

Für die Bildschirmgrösse ist der Inhalt allgemein ziemlich schmal meiner Meinung nach. Könnten wir die Zwischengrössen mal anschauen und  allenfalls anpassen?

Link: https://abonax.ch/ueber-uns/jobs/projektentwicklerin-abonax-club.html

**Comment by Riccardalina** [comment]
Das mit der Inhaltsbreite für die Bildschirmgrösse ist noch nicht geklärt - hatten wir vergessen zu besprechen. Können wir das nächste Woche mal noch anschauen?

**Comment by mguddelmoni** [comment]
Das können wir gerne anschauen, wobei das Problem jetzt etwas entschärft ist, da das Wort nun einfach umbricht wenn es nicht getrennt werden kann.
