### ISSUE TITLE
Kalendereintrag .ics Datei

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#189]
wir würden gerne die möglichkeit haben bei unseren events eine ics datei als download auf desktop und mobile zur verfügung stellen. ics dateien lassen sich zurzeit aber nicht hochladen.. gibt es dafür eine lösung?

Beispiel: https://www.strom.ch/de/veranstaltung/betriebsleitertagung-1

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/ffc8cc66-3ac1-47c6-be40-768b1506bd6e)

**Comment by mguddelmoni** [comment]
Diese Option ist nun in den Events drin.

![Bildschirmfoto 2023-08-30 um 15 08 18](https://github.com/Riccardalina/Abonax-Website/assets/64895942/b86e2ed2-b750-4159-afff-f4adf69f996f)
![Bildschirmfoto 2023-08-30 um 15 08 00](https://github.com/Riccardalina/Abonax-Website/assets/64895942/149f40e6-07d5-4913-ba8f-e5cfed9e92c8)

**Comment by Riccardalina** [comment]
super danke! könntest du das bitte noch gleich machen wie bei dem beispiel? mit dem Text? ausserdem möchte ich die Funktion auch noch als element haben, damit ich die ics datei auch auf der unterseite ergänzen kann.

**Comment by Riccardalina** [comment]
@mguddelmoni könntest du das bitte die tage anschauen? wir würden die gesetzten daten gerne bald kommunizieren

**Comment by mguddelmoni** [comment]
Wie soll denn dieses Element aussehen? 
Ein Button als Content Element?

**Comment by mguddelmoni** [comment]
Ist behoben

**Comment by Riccardalina** [comment]
was ist genau behoben? es sieht immer noch gleich aus auf der event übersichtsseite und ein neues element gibt es nicht oder finde ich es nicht?

**Comment by mguddelmoni** [comment]
Entschuldige. Irgendwie hat GitHub diesen Kommentar ans falsche Ort geschrieben?

**Comment by mguddelmoni** [comment]
Bitte noch die Frage oben beantworten.

**Comment by Riccardalina** [comment]
es sollte gleich aussehen wie bei der vorlage die ich vom beispiel geschickt hatte - geht das?

**Comment by christoph-menzi** [comment]
Icon ist angepasst.

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/6b311e92-8591-4a35-96c5-8fc6096f260e)
