### ISSUE TITLE
Tags auf Teamseite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#190]
wir würden die Mitarbeitenden gerne nach Tags bzw. spezifischen Themen filtern können. Bei den Tags würden die kompetenzen der mitarbeitenden abbilden und wenn man auf einzelne tags klickt, werden nur die mitarbeitenden gezeigt, die diese kompetenzen auch hinterlegt haben. könnte man sowas programmieren? wenn ja wieviel aufwänd wäre das?

**Comment by mguddelmoni** [comment]
Das Tagging ist bereits installiert und muss für den Bereich Mitarbeiter eingebaut werden.
Ich schätze in Etwa einen Aufwand von 4h

- 1h Mitarbeiter Tagging implementieren im Backend
- 3h Frontend Filterung Implementieren

**Comment by Riccardalina** [comment]
Wie ist die Funktion und wie wird es aussehen? Sollten wir das noch etwas genauer definieren? Wie würdest du vorgehen?

**Comment by mguddelmoni** [comment]
@Riccardalina Bitte macht doch ein Layout, wie die Tags dargestellt werden sollen und wie die Liste der Mitarbeiter. 

Ich denke dass das jetzige Layout der Seite wenig geeignet ist für die Filterung, da, wenn die Einträge gefiltert werden, die Links-Rechts Logik nicht mehr funktioniert.

**Comment by mguddelmoni** [comment]
Die Teamseite wurde ja umgebaut. Diese Task scheint also obsolet zu sein
