### ISSUE TITLE
Formulare erstellen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#192]
Wo finde ich die Möglichkeit neue Formulare zu erstellen? ich dachte das hätten wir mal eingebunden, ich kann es aber nicht finden.

**Comment by mguddelmoni** [comment]
Ist nun unter Verwalten drin
![Bildschirmfoto 2023-09-07 um 12 14 30](https://github.com/Riccardalina/Abonax-Website/assets/64895942/41dd7dc8-2b93-4797-b6f0-12de22343406)

**Comment by Riccardalina** [comment]
Hi, die Formulare funktionieren grundsätzlich aber irgendwie kann ich die Anmeldungen im Backend nicht ansehen. Muss dafür noch eine Funktion freigeschalten werden?

**Comment by Riccardalina** [comment]
@mguddelmoni bitte um feedback dazu
