### ISSUE TITLE
CTA unterstrichen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#193]
Waren bei diesem CTA Element die Links nicht einmal unterstrichen?

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/bf7b4ec2-9804-43c4-879e-2f70dcb3d3ce)

**Comment by mguddelmoni** [comment]
Wo ist dieses CTA? Ich finde nur unterstrichene Links

**Comment by Riccardalina** [comment]
jetzt ist es auf einmal wieder unterstrichen - hat sich also erledigt - aus zauberhand
