### ISSUE TITLE
Einbetten Bookings Outlool

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#194]
Ich möchte gerne versuchen das Buchungstool Bookings auf unserer Seite einzubetten. Folgend die Links und Codes:

Link: <a href='https://outlook.office365.com/owa/calendar/AbonaxAG1@abonax.ch/bookings/'>Online planen</a>
iFrame: <iframe src='https://outlook.office365.com/owa/calendar/AbonaxAG1@abonax.ch/bookings/' width='100%' height='100%' scrolling='yes' style='border:0'></iframe>

Ich finde kein Element, mit welchem ich dies einbetten könnte. Bitte um Unterstützung.

**Comment by mguddelmoni** [comment]
Siehe hier:
https://abonax.ch/online-planen.html 

![Bildschirmfoto 2023-09-07 um 12 19 01](https://github.com/Riccardalina/Abonax-Website/assets/64895942/5d646db4-de0a-447e-9a92-f8d37c90e783)
