### ISSUE TITLE
Eventseite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#195]
Bei diesem Event habe ich ein Datum von bis angegeben, angezeigt wird aber nur das von Datum. Link Event: https://www.abonax.ch/events/event-daten/abonax-exkursion-intersolar.html

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/48f7bb00-739d-4f50-b5ee-6546de1fe1a0)

Ausserdem funktioneren im Akkordeon die Aufzählungszeichen nicht:
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/53deabb3-80eb-44e3-9118-3c5c198c1b17)

**Comment by Riccardalina** [comment]
@mguddelmoni Bitte um Feedback dazu

**Comment by Riccardalina** [comment]
@mguddelmoni Bitte um Feedback dazu

**Comment by Riccardalina** [comment]
@mguddelmoni Bitte um Feedback dazu

**Comment by christoph-menzi** [comment]
Die Listen-Elemente haben nun einen Punkt davor:

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/44cc20b2-6a84-4cae-a6a4-b0c05469ecd1)

**Comment by christoph-menzi** [comment]
Nun wird auch das DatumBis angezeigt. Zudem habe ich die Labels davor vereinheitlicht, damit alles auf einer Linie startet.

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/4e000ec9-8142-47d2-95f2-e93472dbabe3)

**Comment by Riccardalina** [comment]
@christoph-menzi danke dir. Das zweite Datum hat nach der Zahl ein Komma anstatt ein Punkt und das KOmma nach 2024 hat ein Leerzeichen zu viel. Kannst du das bitte noch anpassen?

**Comment by christoph-menzi** [comment]
Ist angepasst.
![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/7fbd2883-ab69-4324-9a99-f53714bfb841)
