### ISSUE TITLE
Tags im Club "Branchen-News"

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#196]
Wir merken, dass das so wie angedacht leider nicht gut funktioniert.
Die Tags werden nur pro Seite angezeigt und nicht über sämtliche Beiträge - weshalb ist das so?
Ausserdem möchten wir gerne Tags vordefinieren, die dann nur angewählt werden um nicht bei jedem beitrag neue tags definieren zu müssen - das gerät so leider sehr schnell ausser kontrolle. wäre das möglich umzusetzen?

https://www.abonax.ch/abonax-club/news-radar/

**Comment by Riccardalina** [comment]
@mguddelmoni Bitte um Feedback dazu

**Comment by christoph-menzi** [comment]
Das müsste man entsprechend umbauen. Das funktioniert mit dem aktuell eingesetzten SmartTags so nicht. Diese sind dynamisch. Das ist eigentlich ein Vorteil, aber dafür wie von Dir festgestellt kann es ausser Kontrolle geraten. Ausser Ihr einigt euch auf ein paar wenige SmartTags und nutzt dann immer diese.

Wie auch immer, der Plan B sieht vor, dass man z.B. ein Auswahlfeld mit vordefinierten Auswahl-Felder erstellt.

Welche Tags müssen zur Auswahl stehen?
Kann man eine News nur mit einem Tag versehen oder ist auch eine Mehrfachauswahl möglich?

**Comment by christoph-menzi** [comment]
60 Artikel
Darüber ins Archiv
Im Archiv reduzierte Ausgabe, Titel (text) und Link zu Detailseite

**Comment by mguddelmoni** [comment]
Ich lade nun die Inhalte mit AJAX, somit stimmen die Angegebene Anzahl und alle Artikel werden geladen der aktuellen Tag-Auswahl. Unabhängig ob angezeigt oder nicht.
