### ISSUE TITLE
Titel und Links bei Infoboxen gross

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#197]
Das Element "Infoboxen gross" reagiert bei kleineren Bildschirmgrössen nicht wie gewünscht. Der Titel wird links eingeschoben und der Link unten wird riesig dargestellt. Beispiellink: https://www.abonax.ch/angebot/fachbereiche/

![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/5f6b9878-08f8-48da-8e94-1e5ef53673e7)

**Comment by Riccardalina** [comment]
reminder @mguddelmoni

**Comment by christoph-menzi** [comment]
Fehler wurde behoben.

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/ec1b7cec-cf03-4ce2-8e54-9a6e70b1bd8b)
