### ISSUE TITLE
Spam bei Formularen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#198]
Bei unseren Formularen erhalten wir sehr viele Spamanfragen. Können wir da was machen? 
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/8ea989aa-1ef1-403a-9eaf-d82eb6755771)

**Comment by christoph-menzi** [comment]
Ich habe die Formulare vom Formular-Generator via GoogleReCaptchaV3 erweitert. Wichtig: Die Formulare müssen jeweils beim erstellen angepasst werden mit: recaptchav3

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/95143b9f-6d64-43b6-b4c1-9991ead93b55)

**Comment by christoph-menzi** [comment]
Die Spam-Mails habe ich gelöscht.
