### ISSUE TITLE
Clubbereich

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#199]
wenn man hier auf "Club" klickt öffnet sich eine neue Registerkarte. Wie kann ich das ändern, damit sich die Seite in derselben Registerkarte öffnet?
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/94ac96c5-ebaf-45f9-8b20-4ee5cbbe53d2)

Beim Klicken auf die Unterkategorie "Login Clubbereich" öffnet sich die Seite in derselben Registerkarte. In diesem Fall möchten wir aber, dass sich der Clubbereich in einer neuen Registerkarte öffnet. Wie kann ich das anpassen?
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/dd5ef057-d51a-4635-b62a-313a90a0d5ca)

**Comment by Riccardalina** [comment]
@mguddelmoni oder @christoph-menzi bitte um Feedback dazu

**Comment by Riccardalina** [comment]
@mguddelmoni : Login Clubbereich öffnet sich immer noch in derselben Registerkarte. Gemäss meinen Notizen oben sollte diese Kategorie sich aber in einer neuen Registerkarte öffnen.

**Comment by mguddelmoni** [comment]
Okay, habe den target der falschen Seite hinzugefügt.
Ist angepasst,
