### ISSUE TITLE
Rich Text: Abstand nach Aufzählungen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#202]
Der automatische Abstand nach Aufzählungen ist zu klein. Wenn ich einen Umbruch einfüge ist er wiederum zu gross. Bitte den gleichen Abstand definieren wie wenn ich normalerweise im Text Umbrüche einfüge.
![image](https://github.com/Riccardalina/Abonax-Website/assets/122005698/985249da-33b6-4049-87ef-35dcd190c7cf)

**Comment by christoph-menzi** [comment]
Es neu auch unten einen Abstand.

![image](https://github.com/Riccardalina/Abonax-Website/assets/109087392/c0f7b447-8546-45fe-b668-0df6e196f9a2)
