### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#203]
Wenn Events vorbei sind möchten wir sie in der Regel nicht mehr auf der Website im Eventkalender zeigen. Wenn ich das Häkchen bei "Veröffentlichen" rausnehme erscheinen sie zwar nicht mehr im Kalender aber die Seite ist dann auch nicht mehr erreichbar mit einem Direktlink. Könnte man hier eine Funktion einfügen, dass die Seite noch erreichbar ist aber nicht mehr aktiv im Eventkalender aufgeführt wird?

**Comment by mguddelmoni** [comment]
Ich habe die Ausgabe entsprechend angepasst
Du kannst jetzt auf die Einstellung "Eingeblendet" verwenden und den Artikel auf veröffentlicht lassen.
![Bildschirmfoto 2024-07-25 um 14 28 42](https://github.com/user-attachments/assets/3a8a53b9-eb9c-4ed6-8234-f55db9f7a10b)
