### ISSUE TITLE
Formular wird nicht angezeigt

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#204]
Hallo, ich habe ein neues Formular erstellt.
1. ich kann keine Seite zum weiterleiten auswählen
2. obwohl das formular veröffentlicht wurde wird es nicht angezeigt 

![image](https://github.com/user-attachments/assets/f2600b72-98cb-4c19-b73e-50dcde7618c8)

![image](https://github.com/user-attachments/assets/2161441d-8c57-4a56-8d7c-79b90d44fc6c)

Auf folgender Seite ist das Formular verlinkt: https://www.abonax.ch/kontakt/wettbewerb-stromgesetz-kompass.html

**Comment by mguddelmoni** [comment]
![Bildschirmfoto 2024-08-27 um 16 46 31](https://github.com/user-attachments/assets/8fae79e6-d685-407f-a4f0-cfa67655e532)
Siehe Screenshot: Das Datum für "Unpublish" ist ind er Vergangenheit

**Comment by Riccardalina** [comment]
wow 1970 ist in der tat ein weilchen her :-D danke!
Weiterleiten kann ich aber immer noch nicht weil ich im Feld "weiterleiten zu" keine seite eintragen kann, sie verschwindet jedesmal wenn ich es versuche.

**Comment by mguddelmoni** [comment]
Konnte die Dankesseite auswählen? Habe noch deine Dankesseite für den Wettbewerb erstellt:
https://www.abonax.ch/manager/?a=resource/update&id=822 

https://github.com/user-attachments/assets/7cdc1ecb-5c48-4e8f-9c2d-2bb5471d481d

**Comment by Riccardalina** [comment]
nächstes problem -  die checkboxen werden nicht angezeigt 

![WhatsApp Image 2024-08-28 at 16 16 29](https://github.com/user-attachments/assets/7c8b5d4c-497f-4727-8ae2-20cb58ddfc11)

![image](https://github.com/user-attachments/assets/0ac5f59e-3dda-4795-a37a-fb04b521482f)

**Comment by mguddelmoni** [comment]
Ist erledigt. Es fehlte ein StyleSheet für dieses Element

**Comment by Riccardalina** [comment]
ich kann das formular aber immer noch nicht absenden

**Comment by mguddelmoni** [comment]
![Bildschirmfoto 2024-08-29 um 07 17 16](https://github.com/user-attachments/assets/285fe4f1-cdc5-4178-9aba-c49a82ee2bbf) Das Feld war leer. Wenn das Häkchen gesetzt ist muss auf ein Feld ausgewählt werden an wen diese Mail gesendet werden muss.

**Comment by Riccardalina** [comment]
juhu danke dir
