### ISSUE TITLE
Navigation: Dropdown

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#21]
Bei den Dropdown hatten wir noch einen Pfeil angedacht:

<img width="403" alt="Bildschirm­foto 2023-02-16 um 11 50 59" src="https://user-images.githubusercontent.com/85960512/219345166-17d6a630-06cd-450c-80d8-5fc3683239c5.png">

<img width="417" alt="Bildschirm­foto 2023-02-16 um 11 51 05" src="https://user-images.githubusercontent.com/85960512/219345174-9c60bad1-7095-4262-8c2d-efe4a8ea014a.png">

**Comment by mguddelmoni** [comment]
Bitte den **Browsercache löschen**. Dieser Pfeil ist bereits seit Mittwoch letzter Woche implementiert.
![Bildschirmfoto 2023-02-20 um 15 43 47](https://user-images.githubusercontent.com/64895942/220137121-196dcf5b-72bc-47f7-8a58-9d036813643b.png)
