### ISSUE TITLE
Call to Action: Content Area

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#22]
Der Call to Action in der Content Area passt von Spacing und der Ausrichtung nicht ganz:

<img width="1466" alt="Bildschirm­foto 2023-02-16 um 11 32 03" src="https://user-images.githubusercontent.com/85960512/219340691-c3480053-7097-4919-8543-d4f8a646e779.png">

https://user-images.githubusercontent.com/85960512/219346885-e0a77121-3af5-4e12-be70-76f2e2b5bd4f.mp4

**Comment by mguddelmoni** [comment]
Diese Ansicht ist eine zwischengrösse der Responsive-Ansichten.
Bitte den Browser auf die volle Grösse aufzuziehen.
Dann sieht die Ansicht so aus wie in meinem Screenshot:

![Bildschirmfoto 2023-02-20 um 15 41 05](https://user-images.githubusercontent.com/64895942/220136452-f7b1c9a6-1365-4f95-b831-f721f62dd991.png)

**Comment by alexanderloewe** [comment]
In dem Fall wäre es nicht schlecht, wenn man da einfach nochmals 1 oder 2 Media Queries mehr einsetzt, um das zu verhindern.

**Comment by alexanderbuergin** [comment]
In dem Fall wäre es nicht schlecht, wenn man da einfach nochmals 1 oder 2 Media Queries mehr einsetzt, um das zu verhindern.
