### ISSUE TITLE
Content Area: Spacing

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#23]
https://user-images.githubusercontent.com/85960512/219395554-664f3ef8-930b-41f6-837f-17c9aa2792e3.mp4

**Comment by mguddelmoni** [comment]
Weiteres Layout für das Intro hinzugefügt mit voller Breite

**Comment by alexanderbuergin** [comment]
Allgemein scheint das Problem noch zu bestehen:

<img width="1469" alt="Bildschirm­foto 2023-02-20 um 20 51 20" src="https://user-images.githubusercontent.com/85960512/220188487-8e68ed8f-b680-4663-ad43-bda836198ebc.png">

<img width="1467" alt="Bildschirm­foto 2023-02-20 um 20 51 05" src="https://user-images.githubusercontent.com/85960512/220188481-77bc91a6-5168-434a-bdea-1f4cf231d1d2.png">

<img width="1473" alt="Bildschirm­foto 2023-02-20 um 20 51 13" src="https://user-images.githubusercontent.com/85960512/220188483-3e217816-0fdb-487b-a220-7c7ba68ca9ef.png">
