### ISSUE TITLE
Bild mit CTA Box

### ISSUE THREAD

**Issue by alexanderloewe** [Riccardalina/Abonax-Website#24]
Hier ist die Anzeige auch nicht ganz optimal.

<img width="1306" alt="Bildschirm­foto 2023-02-20 um 15 46 30" src="https://user-images.githubusercontent.com/69263307/220137897-6a09a0d1-12a5-4963-9863-6a4475119bd5.png">

**Comment by alexanderbuergin** [comment]
Die Abstände der Schrift und zwischen den Elementen wirkt noch etwas unharmonisch. Könnte man das noch etwas ausgewogener gestalten?
