### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#28]
Abstand in der zweiten Spalte ist zu gross und bei verkleinerung der breite ist die darstellung nicht mehr einheitlich:

![image](https://user-images.githubusercontent.com/122005698/220920945-c6362f71-5abb-4fd4-a1a8-98ab20becda2.png)

**Comment by Riccardalina** [comment]
@mguddelmoni ist das behoben? ich sehe noch keinen unterschied.
bitte tickets erst schliessen, wenn behoben

**Comment by mguddelmoni** [comment]
Bitte den Browsercache löschen.
Ebenfalls währe hilfreich zu wissen in welchem Browser das so aussieht.
Getestet auf Fireworks, Chrome, Safari. Überall sieht es so aus wi in meinem Screenshot!

![Bildschirmfoto 2023-02-23 um 15 21 29](https://user-images.githubusercontent.com/64895942/220934801-a9dd258f-15d5-4187-bef3-508dd94d5232.png)
