### ISSUE TITLE
Archivfunktion Events

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#3]
Button fehlt bzw. ist die Archivfunktion für Events verfügbar?

![grafik](https://user-images.githubusercontent.com/122005698/218456648-16734667-d3b6-4c68-8797-a5268f03692e.png)

**Comment by mguddelmoni** [comment]
Dieser Button ist auf der Startseite vorhanden.
Auf der Events Seite selbst ist kein Button im Layout.
https://xd.adobe.com/view/25d20ab7-018b-4802-a34f-4ffe24c154b1-7081/screen/5a3794c1-0663-43aa-9755-40f958ae5064/specs/  

Ein Archiv gibt es nicht. Das müssen wir erstellen und eine Archivfunktion dazu bauen.
Soll eine Seite mit Abgelaufenen Events erstellt werden?

**Comment by Riccardalina** [comment]
dann hab ich das falsch interpretiert und wir können das so sein lassen
