### ISSUE TITLE
Timeline: Darstellung

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#35]
Bei der Darstellung der Timeline hapert es noch:

<img width="618" alt="Bildschirm­foto 2023-03-06 um 18 02 34" src="https://user-images.githubusercontent.com/85960512/223179795-0e08d579-048c-4fff-9fbd-8021414220f0.png">

Cache habe ich geleert.

**Comment by mguddelmoni** [comment]
Erledigt
![Bildschirmfoto 2023-03-21 um 15 28 49](https://user-images.githubusercontent.com/64895942/226638350-5f034571-da37-4523-a4c9-d11cda6d76c8.png)
