### ISSUE TITLE
Titel/Liste Abstand

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#36]
Der Abstand nach dem Titel zur Liste ist noch sehr eng:

<img width="427" alt="Bildschirm­foto 2023-03-06 um 18 01 27" src="https://user-images.githubusercontent.com/85960512/223180166-fb5a04a8-c46c-482c-9213-39758d3e4eb0.png">

<img width="1471" alt="Bildschirm­foto 2023-03-06 um 18 01 17" src="https://user-images.githubusercontent.com/85960512/223180242-df84c7d1-a47f-49da-a853-eb936b238fe6.png">

**Comment by mguddelmoni** [comment]
Ich finde diesen Abschnitt nirgends. Bitte jeweils die Links zu den issues posten.

**Comment by alexanderbuergin** [comment]
Hier:
https://abonax2023.visions.page
