### ISSUE TITLE
Teamseite: Reihenfolge definieren

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#38]
Auf der Teamseite kann ich keine Reihenfolge der Mitarbeitenden definieren. gibt es dafür keine Funktion? ansonsten müsste ich bei neuen Mitarbeitenden immer komplett von vorne anfangen - wir würden das gerne nach ABC sortieren

![image](https://user-images.githubusercontent.com/122005698/224295496-d0177961-156c-4dbd-a7de-b971e5f2c25c.png)

**Comment by Riccardalina** [comment]
PS: Gleiches Problem haben wir auch bei der Eventseite

**Comment by Riccardalina** [comment]
PPS: Gleiches Problem bei Aktuelles

**Comment by mguddelmoni** [comment]
Sortierung aktiviert im Backend (Drag and Drop)
