### ISSUE TITLE
Anzeige neuer Inhalte im Footer

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#4]
Die Anzeige in Form von Zahlen im Footer fehlt

vgl. Vorlage vs. aktuelle Website

![grafik](https://user-images.githubusercontent.com/122005698/218457245-e6fe7eb7-c715-4924-9d1f-16016017e3c6.png)
![grafik](https://user-images.githubusercontent.com/122005698/218457300-044583da-4059-4a22-8402-ee46a45e0f50.png)

**Comment by mguddelmoni** [comment]
Die Badges sind nun drin. aber es gibt kein Modul für Karriere. Ebenfalls fehlt das Layout dieser Seite.
Damit ich die Anzahl Jobs zählen kann brauche ich ein entsprechendes Listenmodul. (Momentan Weden die Events gezählt)

**Comment by alexanderbuergin** [comment]
Hier haben wir noch ein Anzeigeproblem mit den Elementen. Diese sollten als Budget positioniert sein:

<img width="157" alt="Bildschirm­foto 2023-02-16 um 09 50 25" src="https://user-images.githubusercontent.com/85960512/219320989-6f00a1d8-2eab-43c8-9f13-f39fe961f4a4.png">

**Comment by mguddelmoni** [comment]
Bitte den Cache leeren.
![Bildschirmfoto 2023-02-21 um 08 59 18](https://user-images.githubusercontent.com/64895942/220283357-f04ac4c5-03b7-4568-8a87-ffd52de0f9d2.png)
