### ISSUE TITLE
Eventseite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#48]
Wie es aussieht:

![image](https://user-images.githubusercontent.com/122005698/224632026-c9ae9258-c7b3-4fad-a62f-9cb2d1ceae4e.png)

Textbreite
Titelschrift
Abstand von Text zu Aufzählung nicht änderbar....
....

Wie es aussehen sollte:

![image](https://user-images.githubusercontent.com/122005698/224632107-039534fd-ab34-4693-87d3-de72a4fa7546.png)

**Comment by mguddelmoni** [comment]
**Stift + Enter für Zeilenumbrüche**. leere Absätze werden nicht dargestellt.
