### ISSUE TITLE
Logo Konfigurator

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#49]
Wie kann man hier Logos hinzufügen oder ändern?
![image](https://user-images.githubusercontent.com/122005698/224632696-9c2f528a-d5c3-4e85-9a91-2a591f42c8e5.png)

**Comment by mguddelmoni** [comment]
![Bildschirmfoto 2023-03-21 um 15 31 32](https://user-images.githubusercontent.com/64895942/226639232-4cb5553f-4dac-402a-a7e7-6697ee0994ab.png)
