### ISSUE TITLE
Design Testimonials

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#5]
Testimonial Sprechblasen sehen anders aus als in der Vorlage, bitte gemäss Vorlage designen. Ausserdem fehlen gemäss Vorlage die darunter folgenden Darstellungswiesen.

Aktuell:
![grafik](https://user-images.githubusercontent.com/122005698/218463943-85c8f029-f5f2-4910-ab02-ce58d1c73949.png)

Vorlage:
![grafik](https://user-images.githubusercontent.com/122005698/218463997-882ca215-8850-4e23-a514-64e7ddcca642.png)

**Comment by mguddelmoni** [comment]
Fas Element existiert.
Es gibt im XD zwar bei den Inhalten keine Seite mit diesen Blöcken UND der linken Infospalte.
Ich habe das Element aber nun hinzugefügt, damit Ihr diese anschauen könnt.
