### ISSUE TITLE
Navigationslinks Unterseiten

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#50]
Wo finde ich diesen Balken mit den Unterthemen bzw. wie kann ich ihn aktivieren und befüllen?

![image](https://user-images.githubusercontent.com/122005698/224636225-5382d55c-2fd8-4cf1-9398-b6fb906585fd.png)

**Comment by mguddelmoni** [comment]
Bitte gib mir jeweils den Link an zu den jeweils referenzierten Seiten

**Comment by Riccardalina** [comment]
gilt für alle seiten innerhalb von der kategorie angebot

https://abonax2023.visions.page/angebot/produkte/energieloesungen-neu.html

**Comment by Riccardalina** [comment]
https://abonax2023.visions.page/angebot/produkte/energieloesungen-neu.html

**Comment by mguddelmoni** [comment]
In den Einstellungen der Seite aktivieren und bei den Headings und Ankern die Option "Im Ankermenu anzeigen" auswählen

![Bildschirmfoto 2023-03-21 um 14 12 07](https://user-images.githubusercontent.com/64895942/226616735-9b1b6bbc-0744-452b-9521-cd75a9b86b3a.png)
![Bildschirmfoto 2023-03-21 um 14 11 41](https://user-images.githubusercontent.com/64895942/226616742-b76fbcdd-d16b-4b44-9480-b2c07b243565.png)

PS: Es gibt keine Mobile Ansicht zu diesem Element,
