### ISSUE TITLE
Bilder im CTA

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#54]
Die Fotos im CTA haben eine schlechte Qualität - woran liegt das?

![image](https://user-images.githubusercontent.com/122005698/224651825-6968893d-ede4-407d-9762-f136e392bc3e.png)

Link: https://abonax2023.visions.page/angebot/produkte/energieloesungen-neu.html

**Comment by mguddelmoni** [comment]
Bils wurde nicht komprimiert 6000 pixel bei 200 DPI). Wird nun vom CMS heruntergerechnet auf ein Webtaugliches Format
