### ISSUE TITLE
Teamseite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#56]
Schriftart sieht noch immer anders aus als in der Vorlage und Text ist breiter als in der Vorlage:

![image](https://user-images.githubusercontent.com/122005698/224665218-50a1c912-c6ef-450f-a430-743996cea9d3.png)

![image](https://user-images.githubusercontent.com/122005698/224665320-fbc5fd74-9a30-4387-9db5-74d06fa775e6.png)

**Comment by mguddelmoni** [comment]
Ansicht ist angepasst.
Hier der direkte Vergleich:
![Bildschirmfoto 2023-03-21 um 10 53 03](https://user-images.githubusercontent.com/64895942/226571507-c0e9d4c7-1f22-4977-89f7-c8ec3df693f1.png)
