### ISSUE TITLE
Abstand zwischen Titel und Aufzählung

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#57]
Abstand nicht einstellbar:

![image](https://user-images.githubusercontent.com/122005698/224669137-cd4651f5-ef83-4281-9080-53c095ff68fb.png)

Vorlage:
![image](https://user-images.githubusercontent.com/122005698/224669242-789be8e1-b109-4ef7-9661-a17271b9f1bf.png)

Link: https://abonax2023.visions.page/angebot/services/betriebsfuehrung.html

**Comment by mguddelmoni** [comment]
Abstände vergrössert, Aufzählungen mit langem Gedankenstrich, in den Blauen Boxen mit Grünem Punkt
