### ISSUE TITLE
Abstände im Richtext zwischen Titel und Text

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#58]
Ansicht Backend: Abstand zwischen Titel und Text ist gross
![image](https://user-images.githubusercontent.com/122005698/224672507-31e322af-f228-4fd4-afc5-668a2e2dc7ff.png)

Ansicht Frontend: Abstand zwischen Titel und Text nicht vorhanden
![image](https://user-images.githubusercontent.com/122005698/224672596-0fccd2c2-ae23-43cf-8f0b-9bd69dde2066.png)

Link: https://abonax2023.visions.page/angebot/services/betriebsfuehrung.html

**Comment by mguddelmoni** [comment]
Leere Absätze wurden nicht dargestellt. Ist behoben
Es gibt übrigens Enter (Neue Absatz) und SHIFT Enter (Linienumbruch)
