### ISSUE TITLE
Textabstand links und rechts

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#59]
Gemäss Vorlage sind die Textabstände nach links grösser.

Vorlage: https://xd.adobe.com/view/a073a1cb-caa3-4129-9326-cc28bde3d14f-f520/screen/50b229d4-3084-4bb1-b91f-3b0a7e110b32
![image](https://user-images.githubusercontent.com/122005698/224697393-e8218a18-684d-4cba-a89d-7b74130a977c.png)

Darstellung jetzt im Frontend:
![image](https://user-images.githubusercontent.com/122005698/224697506-8c03d759-609a-446b-ae42-c3cc92577cb4.png)

Die Videovorschau hat ausserdem nicht dieselber Grösse bzw. ist jetzt im Frontend grösser als auf der Vorlage.

**Comment by Riccardalina** [comment]
bitte nochmals von grundauf prüfen und gemäss vorlage anpassen

**Comment by mguddelmoni** [comment]
Auf https://abonax2023.visions.page/angebot/produkte/erkloervideos-neu.html ist das richtig umgesetzt.
Linke Spalte 1 Spaltenbreite, rechte Spalte 7 (11 Tablet, 12 Mobile)

Werde die Vorlagen ganz am Schluss entsprechend anpassen
