### ISSUE TITLE
Bildrahmen bei Hoover

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#60]
Wenn man über die Kachel hoovert, hat das Bild unten einen weissen Rahmen bzw. alle Bilder haben das.

![image](https://user-images.githubusercontent.com/122005698/225543456-4940c137-5e1f-4f69-8918-550799eab623.png)

Link. https://abonax2023.visions.page/aktuelles/

**Comment by mguddelmoni** [comment]
Bitte Cache leeren. Dieses Issue ist bereits behoben
