### ISSUE TITLE
Video im Intro

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#61]
Wenn ich hier einen Youtube link einfüge wird das Video nicht angezeigt:

![image](https://user-images.githubusercontent.com/122005698/225938071-a8683c3d-02aa-4061-bfed-079894f2c077.png)

Findest du auf der Startseite

**Comment by mguddelmoni** [comment]
Ein solches Element war nicht vorgesehen. 
Das Video war nur für die Variante  "Video Rechts und Inhalt Links"
Habe nun aber eines Variante erstellt. Wenn ein Video angegeben wird, übersteuert das Video das Bild
