### ISSUE TITLE
Reihenfolge Events

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#62]
Ich verstehe leider nicht wie die Logik der Reihenfolge funktioniert. Die Events werden nicht in derselben Reihenfolge wie erstellt und auch nicht in der Reihenfolge der Daten sortiert... kannst du da eine sinnvolle logik reinbringen? sortiert nach Datum wann die Events stattfinden vielleicht?

https://abonax2023.visions.page/events.html

**Comment by mguddelmoni** [comment]
Sortiert nun nach Datum Start
