### ISSUE TITLE
Richtexte auf ganzer Seitenbreite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#63]
Ich verstehe nicht was hier das problem ist, der Text fügt sich auf die gesamte breite ein. Es muss doch sein, dass ich ganz einfach Richtext hinzufügen kann, der sich der Seite und den Spacingvorgaben automatisch anpasst??

![image](https://user-images.githubusercontent.com/122005698/225947444-0b7fead3-f068-416c-bb01-ae3f02549b22.png)

Link: https://abonax2023.visions.page/ueber-uns/jobs/

**Comment by mguddelmoni** [comment]
Seite nochmals gespeichert. Dann ist das Layout wieder gesetzt. Durch die Änderungen an Contentblocks haben die Einstellungen zum Teil geändert. Durch das Speichern werden die Einstellungen wieder gesetzt.
