### ISSUE TITLE
Anker auf Angebotsseiten

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#64]
Welche Logik ist hier dahinter? Das sind die falschen Unterkategorien die es nimmt.

![image](https://user-images.githubusercontent.com/122005698/227446582-aa240b94-e109-4669-827d-86d092e24efb.png)

es sollte diese Unterkategorien nehmen:
![image](https://user-images.githubusercontent.com/122005698/227446638-829e7660-93db-4dcc-9795-67b17e75f058.png)

Seite: https://abonax2023.visions.page/angebot/produkte/energieloesungen-neu.html

Wenn etwas unklar ist, bitte immer vorher fragen..

**Comment by Riccardalina** [comment]
Der Balken klebt am Navigationsmenü sobald man runterscrollt - da sollte ein Abstand sein wie in der Vorlage. Ausserdem sieht der Pfeil rechts nicht gleich auf wie auf der Vorlage.

**Comment by Riccardalina** [comment]
Es wird auch nicht unterstrichen wenn man es anklickt.

**Comment by Riccardalina** [comment]
meiner meinung nach stimmt auch der Schrifttyp nicht

**Comment by mguddelmoni** [comment]
Beschrieben, wie es funktioniert ist hier:
https://github.com/Riccardalina/Abonax-Website/issues/50 Layout schaut sich Chris noch an
