### ISSUE TITLE
Smart Tags im Clubbereich

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#65]
Die Smart Tags werden erst ab zwei Artikel welche den Tag hinterlegt haben angezeigt. Ausserdem zeigt es nie mehr als 10 oder 11 Tags an. Kann es sein, dass wir da eine Beschränkung drin haben?

![image](https://user-images.githubusercontent.com/122005698/233913903-c92b5164-da33-488a-9de4-d0dad91d63e9.png)
https://abonax2023.visions.page/abonax-club/news-radar/

**Comment by christoph-menzi** [comment]
@mguddelmoni Das müsstest Du Dir kurz anschauen!

**Comment by mguddelmoni** [comment]
Das Problem ist behoben
