### ISSUE TITLE
Element: Call to action 

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#66]
Die Einstellungen im Call to action Element sind verwirrend:

- Mit "Link (Button)" wird "Link (Text)" angepasst und umgekehrt
- ausserdem lässt sich die Linkbeschriftung nicht anpassen. Es steht immer "mehr erfahren"

![image](https://user-images.githubusercontent.com/122005698/233955468-7833ecc6-8277-49a0-933b-95b6b4a645e2.png)

Link: https://abonax2023.visions.page/angebot/produkte/solargemeinschaft.html

**Comment by christoph-menzi** [comment]
Es gibt 2 verschiedene Link/Button typen. 

Der Text kann jeweils in der Link-Beschriftung definiert werden.

![image](https://user-images.githubusercontent.com/109087392/234199741-f6d34ec1-8f9f-4722-a9ee-bda9b80ac86c.png)

**Comment by Riccardalina** [comment]
das hab ich gesehen, es funktioniert aber nicht

**Comment by christoph-menzi** [comment]
Was genau funktioniert nicht? Ich kann die einzelnen Links definieren und diese werden dann bei mir ausgegeben. Bitte genaueren Beschrieb für das Problem.

![image](https://user-images.githubusercontent.com/109087392/235160001-0580c084-8b84-4497-b7ee-c17224030727.png)
![image](https://user-images.githubusercontent.com/109087392/235160037-32eb5939-b104-469b-a4c0-f155b7a5e7a1.png)

**Comment by Riccardalina** [comment]
> https://abonax2023.visions.page/angebot/produkte/solargemeinschaft.html

wenn du nur einen Link bei "Link (Button" setzt und bei "Link Beschriftung Button" einen Text eingibst, übernimmt es diesen nicht im Button. Es steht dann immer "mehr erfahren". Beispiel hier ganz unten: https://abonax2023.visions.page/angebot/produkte/erklaervideos.html

**Comment by christoph-menzi** [comment]
War verkehrt rum, habs nun richtig gedreht. :-)

**Comment by Riccardalina** [comment]
bei mir funktioniert es immer noch nicht - mach ich etwas falsch?

![image](https://user-images.githubusercontent.com/122005698/235173625-da5cb4f4-fb76-4c99-a841-31010382b8cd.png)

**Comment by christoph-menzi** [comment]
Ich bin mir nicht sicher was genau schief läuft bei Dir. Bei mir funktioniert das mit der Link-Definiton.

![image](https://user-images.githubusercontent.com/109087392/235179395-ebec93d9-c0b6-4ad7-817a-f45708ef8fdd.png)

**Comment by christoph-menzi** [comment]
Ah, noch ein Bug gefunden. Jetzt aber müsste es klappen.

**Comment by Riccardalina** [comment]
ok jetzt funktioniert der text. aber die funktion "grösse wählen" funktioniert bei mir auch nicht und wenn ich richtext eingebe erscheint der auch nirgends im CTA

**Comment by Riccardalina** [comment]
in einem neuen fenster wird der externe link auch nicht geöffnet wenn ich diese funktion definiere

**Comment by christoph-menzi** [comment]
Irgendwie funktioniert das bei mir mit dem Fenster öffnen. Wurde das vermutlich schon gefixt?

Version klein und gross, es ändert sich schon was. Siehe Vorlage. Auch in der Live-Version.

![image](https://user-images.githubusercontent.com/109087392/236487169-c0b5077d-7b95-416d-8227-3e24aa963a69.png)
