### ISSUE TITLE
Element: Violette Box mit Buchstaben

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#67]
Bild im Buchstaben wird verpixelt dargestellt, auch wenn Qualität gut ist. Bitte bei allen Elementen mit Buchstaben und Bildern im Hintergrund prüfen.

![image](https://user-images.githubusercontent.com/122005698/233974645-d7e3e512-7c0f-4aa2-b416-2809abe76761.png)

Link: https://abonax2023.visions.page/angebot/produkte/solargemeinschaft.html

**Comment by Riccardalina** [comment]
Die Bilder werden zudem immer noch sehr gross dargestellt, sodass es stark reinzoomt und somit kein wirkliches motiv erkennbar ist. kann man das nicht verkleinern bzw. im hintergrund weniger gross darstellen?

**Comment by Riccardalina** [comment]
Vergleich aktuelle Ansicht:
![image](https://user-images.githubusercontent.com/122005698/234005919-4886a93c-64a8-42aa-abdd-96416cda9d3b.png)


Zu Ansicht gemäss Vorlage:
![image](https://user-images.githubusercontent.com/122005698/234005972-02195d6e-e0ca-4e4b-b686-9c5e0d07fb1f.png)


Unterschiede: Positionierung der Buchstaben, Bildqualität und Bildgrösse

**Comment by christoph-menzi** [comment]
Wir richten die Buchstaben am Bildschirmrand aus. Ein "ze" und "me" sind unterschiedlich lange. Ein "me" ist länger und würde bis zur violetten Box gehen.

Option 1: Buchstaben werden am Bildschirmrand ausgerichtet (aktuell)
Option 2: Buchstaben werden an der Mitte ausgerichtet

Bei der Option 2 gibt es dann je nach Buchstabenkombi links/rechts weissen Rand. "ze" z.B. wäre zu kurz und hätte dann im oben bebilderten Beispiel dann einen weissen Rand auf der rechten Seite.

**Comment by Riccardalina** [comment]
@christoph-menzi: ich verstehe die herausforderung mit den verschiedenen buchstaben aber wie du im vergleich oben sehen kannst, sind sie auch von der position her in der höhe anders platziert. ausserdem haben wir auch das problem, dass die bilder zu stark hereingezoomt werden und mach erstens nichts erkennen kann und zweitens auch hochauflösende bilder verpixelt sind. was kannst du da machen?

**Comment by christoph-menzi** [comment]
Ich habe nun die Auflösung um einiges erhöht und die Violette Box weiter nach unten platziert. So okey?
![image](https://user-images.githubusercontent.com/109087392/235163556-02d12868-fa3c-4b76-bad0-ef73f0128829.png)

https://abonax2023.visions.page/dev/test.html

**Comment by Riccardalina** [comment]
> Ich habe nun die Auflösung um einiges erhöht und die Violette Box weiter nach unten platziert. So okey? ![image](https://user-images.githubusercontent.com/109087392/235163556-02d12868-fa3c-4b76-bad0-ef73f0128829.png)
> 
> https://abonax2023.visions.page/dev/test.html

es sieht schon etwas besser aus, meiner meinung nach ist das bild aber immernoch sehr gross bzw. hat einen starken zoom im hintergrund. findest du nicht auch, dass so ist im vergleich zur vorlage?

**Comment by christoph-menzi** [comment]
Die Gestaltung im Grafik-Programm Adobe XD und die Webseite kannst Du in dem Fall nicht 1:1 vergleichen.  
Ganz speziell mit den ausgeschnittenen Buchstaben wird es schwierig hier die Vorlage ohne Abweichung umzusetzen. Jedenfalls wüsste ich im Moment nicht wie. 

Das Buchstaben Element ist eigentlich viel höher. Im oben gezeigten Beispiel haben wir 2 kleine Buchstaben. Die effektive Grösse vom Element siehst Du im Bild unten. Danach richten wir das Bild am Element mittig aus. Und wir strecken das Bild damit es alle Buchstaben abdeckt. 

Ich könnte die BIldstreckung entfernen, aber ich kann Dir dann nicht garantieren dass es dann bei den einzelnen Displaygrössen und auf den verschiedenen Endgeräten sauber funktioniert.

![image](https://user-images.githubusercontent.com/109087392/235165812-63bf02ed-d0af-4634-a3f6-37be5cfc1e0b.png)

**Comment by Riccardalina** [comment]
> Die Gestaltung im Grafik-Programm Adobe XD und die Webseite kannst Du in dem Fall nicht 1:1 vergleichen. Ganz speziell mit den ausgeschnittenen Buchstaben wird es schwierig hier die Vorlage ohne Abweichung umzusetzen. Jedenfalls wüsste ich im Moment nicht wie.
> 
> Das Buchstaben Element ist eigentlich viel höher. Im oben gezeigten Beispiel haben wir 2 kleine Buchstaben. Die effektive Grösse vom Element siehst Du im Bild unten. Danach richten wir das Bild am Element mittig aus. Und wir strecken das Bild damit es alle Buchstaben abdeckt.
> 
> Ich könnte die BIldstreckung entfernen, aber ich kann Dir dann nicht garantieren dass es dann bei den einzelnen Displaygrössen und auf den verschiedenen Endgeräten sauber funktioniert.
> 
> ![image](https://user-images.githubusercontent.com/109087392/235165812-63bf02ed-d0af-4634-a3f6-37be5cfc1e0b.png)

ok dann lassen wir es mal so wie es ist, danke dir
