### ISSUE TITLE
Geschäftsfeld Unterseite: Schrifttypen

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#70]
Die Schrifttypen stimmen nicht mit der Vorlage überein.

Aktuell:
![image](https://user-images.githubusercontent.com/122005698/234029885-ff9de1ce-401e-4398-8555-67ba96545be1.png)

Vorlage:
![image](https://user-images.githubusercontent.com/122005698/234030119-0019d7d5-2c16-4ba2-98b1-930c30466acb.png)

Link: https://abonax2023.visions.page/angebot/fachbereiche/waerme.html

**Comment by christoph-menzi** [comment]
Die Schriftgrösse kann angepasst werden beim Headline-ELement.

Accordion-Titel habe ich nun "bold" hinterlegt.

![image](https://user-images.githubusercontent.com/109087392/235111085-13c1c68a-8e80-4053-bb4a-caa8734c8c41.png)
