### ISSUE TITLE
Timeline: .timeline li .direction-r  -> 100% width

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#71]
Die Timeline Items bitte auf 100 % width, so sieht es etwas komisch aus, da asymmetrisch.

<img width="1334" alt="Bildschirm­foto 2023-04-27 um 00 45 44" src="https://user-images.githubusercontent.com/85960512/234718914-ce9dbf00-f6a6-45c2-b29a-607ddabc6531.png">
<img width="376" alt="Bildschirm­foto 2023-04-27 um 00 45 57" src="https://user-images.githubusercontent.com/85960512/234718917-a73fcfdc-3139-4b78-963a-52c7fe440bb3.png">

**Comment by christoph-menzi** [comment]
Ist angepasst.

**Comment by christoph-menzi** [comment]
![image](https://user-images.githubusercontent.com/109087392/235109893-f1f333ae-a251-4fd0-9237-d01bf49d91e8.png)
