### ISSUE TITLE
Favicon: Ergänzen

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#72]
<img width="198" alt="Bildschirm­foto 2023-04-27 um 00 45 03" src="https://user-images.githubusercontent.com/85960512/234719054-afefe107-11ea-42bd-9add-a28538d9e09a.png">

**Comment by christoph-menzi** [comment]
Welches Favicon? Wieder das alte "+" Zeichen? Oder gibt es ein anderes Favicon?

**Comment by alexanderbuergin** [comment]
Okay, dann hat das Favicon den Weg zu dir nicht geschafft:

https://www.dropbox.com/t/7opt7aLEBI3b8iPQ
https://www.dropbox.com/t/q3gl57oZAKS0kNFO

Wenn du ein anderes Format von mir brauchst, melde dich.

**Comment by christoph-menzi** [comment]
ok, ist eingebaut.
