### ISSUE TITLE
Club Login

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#73]
Beim Login für den Club ist das Formular extrem schmal und die Schriften etwas gross.

Man sollte sicher mindestens die Breite des Formulars auf min 500px (max-width, wegen RWD) vergrössern.

<img width="1474" alt="Bildschirm­foto 2023-04-27 um 00 57 26" src="https://user-images.githubusercontent.com/85960512/234720168-9d54e719-8a33-4784-a318-3b7123ef64a5.png">

**Comment by christoph-menzi** [comment]
Ist angepasst. Mit der neuen Breite gibt keine Textumbrüche mehr. Trotzdem die Schrift noch verkleinern?

**Comment by alexanderbuergin** [comment]
So sieht es gut aus 👍🏻

**Comment by alexanderbuergin** [comment]
Auf kleinerem Bildschirm habe ich es geschafft dies zu erzeugen:

<img width="996" alt="Bildschirm­foto 2023-04-28 um 11 58 31" src="https://user-images.githubusercontent.com/85960512/235117746-cff2965f-47f0-4e3f-9bb6-dbfe011df221.png">

Eventuell einfach den body bg auf dieselbe Farbe stellen

**Comment by christoph-menzi** [comment]
Ich habs mal so angepasst. Scheint soweit zu funktionieren.

**Comment by alexanderbuergin** [comment]
Was wir nun dafür haben ist, dass das Bild 100vh ist auf Mobile, was nicht praktisch ist

**Comment by christoph-menzi** [comment]
Ich habe es für Smartphone angepasst. 50vh

![image](https://user-images.githubusercontent.com/109087392/235136624-af32bfa6-d61d-46c3-b701-44865b8b4c0a.png)

**Comment by alexanderbuergin** [comment]
https://abonax2023.visions.page/abonax-club/login/

**Comment by alexanderbuergin** [comment]
Ich habe hier nochmals etwas gefunden:

<img width="1008" alt="Bildschirm­foto 2023-05-08 um 11 17 46" src="https://user-images.githubusercontent.com/85960512/236786570-81b29a87-ef78-4c58-bda8-4b81c6be1300.png">
