### ISSUE TITLE
Club Login: Seitenbar

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#74]
Die block-club-popup sollte selbst ein overflow-x: scroll; haben.

So zerreist es alles:

<img width="1472" alt="Bildschirm­foto 2023-04-27 um 00 58 06" src="https://user-images.githubusercontent.com/85960512/234720292-326aeaeb-20ed-4832-806c-030094021c1d.png">

**Comment by christoph-menzi** [comment]
Ist angepasst.

**Comment by alexanderbuergin** [comment]
Top, danke
