### ISSUE TITLE
Spacer wenn kein Header

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#75]
Eine Seite sollte immer einen Spacer nach oben haben, wenn kein Header/Header-Bild auf der Seite ist.

So passiert dies nicht:

https://abonax2023.visions.page/dsgvo.html

<img width="1480" alt="Bildschirm­foto 2023-04-27 um 01 00 36" src="https://user-images.githubusercontent.com/85960512/234720607-9019ebbe-419f-4fc8-ac2d-b3edbcc81e50.png">

**Comment by christoph-menzi** [comment]
Die Seite wird via Layouts aufgebaut. Grundsätzlich gibt es im Normfallfall IMMER ein Intro-Element.

In dem Fall wäre es das Introelement "Titel & Text" > https://abonax2023.visions.page/dsgvo.html

![image](https://user-images.githubusercontent.com/109087392/235106123-0a9956a5-b31b-4c27-bf90-914d111d1939.png)
![image](https://user-images.githubusercontent.com/109087392/235106219-12fd27ee-df17-4188-bf79-d79954e342db.png)

**Comment by alexanderbuergin** [comment]
Okay, dann passt das so.
