### ISSUE TITLE
Leerräume

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#76]
Auf dieser Seite hat es einen Leerraum, ich weiss nicht, ob dies auch auf anderen Seiten so ist. Es sollte eigentlich keine Abstände an solchen Orten haben:

https://abonax2023.visions.page/aktuelles/

<img width="1469" alt="Bildschirm­foto 2023-04-27 um 01 02 04" src="https://user-images.githubusercontent.com/85960512/234720915-e966a0e4-5399-4d2e-a7b3-a069ceaa5f96.png">

**Comment by christoph-menzi** [comment]
Jedes Element hat eine Einstellung  Abstand nach unten Ja/nein und welche Grösse. Ich habe den Abstand entfernt. https://abonax2023.visions.page/aktuelles/
