### ISSUE TITLE
Newsletter Sub Formular

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#77]
Auf dieser Seite hat es ein Newsletter Sub Formular, hier ein paar Bemerkungen:

https://abonax2023.visions.page/aktuelles/

Statt dem `x` nehmt bitte ein `×`(Multiplizieren Symbol, sieht schöner aus):

<img width="87" alt="Bildschirm­foto 2023-04-27 um 01 03 36" src="https://user-images.githubusercontent.com/85960512/234721082-41260326-e499-4f00-a10d-a810594cec8c.png">

---

Die Anrede sollte ein Dropdown sein:

---

<img width="831" alt="Bildschirm­foto 2023-04-27 um 01 03 55" src="https://user-images.githubusercontent.com/85960512/234721177-563515d2-5a07-4cd2-a04d-98692276145e.png">

Nach der Anmeldung sollte man auf eine Opt-in Page kommen. 
Auf dieser sollte man sich für die Anmeldung bedanken. 
Wenn Double-Opt-in sollte man ihnen mitteilen, dass die ihre E-Mail noch bestätigen sollten.

---

Die Abstände sind hier zu gross, es sieht unharmonisch aus.

<img width="828" alt="Bildschirm­foto 2023-04-27 um 01 07 34" src="https://user-images.githubusercontent.com/85960512/234721492-fd01f7cb-e3cf-4857-aa7d-c964beff4d60.png">

**Comment by christoph-menzi** [comment]
Abstände und select-field habe ich korrigiert/erweitert. Restlichen Sachen dann an Mikro.
