### ISSUE TITLE
Job Seite

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#78]
Aus der Job-Seite haben die Texte unterschiedliche Breiten, dass sieht so nicht optimal aus, bitte alle Texte in der schmalen Breite:

https://abonax2023.visions.page/ueber-uns/jobs/

---

Bei der Box sind die Schriftgrössen komisch proportioniert. Bitte Pensum, Text und Button gleichmässig.

<img width="1329" alt="Bildschirm­foto 2023-04-27 um 01 09 59" src="https://user-images.githubusercontent.com/85960512/234721681-56bf527e-fd43-4d3b-bfbb-b98d98573b5a.png">

Zudem sollten die paddings der Box grösser und gleichmässig (unten ist der grösser) sein: Etwas um die 3rem

**Comment by christoph-menzi** [comment]
Abstände, Padding, und Schriftgrösse vereinheitlicht

![image](https://user-images.githubusercontent.com/109087392/235100069-94523655-0505-4827-b782-00617147ef98.png)

**Comment by alexanderbuergin** [comment]
Hier habe ich ebenfalls noch ein Missverständnis geschaffen. Den Button natürlich bold ;)

Danke

<img width="1394" alt="Bildschirm­foto 2023-04-28 um 14 39 11" src="https://user-images.githubusercontent.com/85960512/235149649-c02ddf19-82d4-4cf6-a0d3-f77f920c9f97.png">

**Comment by christoph-menzi** [comment]
Ok, ist wieder bold. :-)
