### ISSUE TITLE
Newsletter Seite

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#79]
Die Seite sieht so nicht sehr vorteilhaft aus.

https://abonax2023.visions.page/ueber-uns/newsletter-der-schule-wartau/

Könnte man allenfalls das Formular direkt auf der Seite platzieren, ohne PopUp?

**Comment by christoph-menzi** [comment]
Also der Abstand oben ist korrigierbar. Man könnte das Formular auch unten platzieren. Also ohne Popup. Soll das Formular dann DIREKT in die violette Box platziert werden?

![image](https://user-images.githubusercontent.com/109087392/235091819-69fb521c-fb4c-4e49-bf0d-4d9e2bcaeb02.png)

**Comment by christoph-menzi** [comment]
Die Violette Box wäre dann entsprechend höher.

**Comment by alexanderbuergin** [comment]
Dies könnte eine Lösung sein:

<img width="1471" alt="Bildschirm­foto 2023-04-28 um 14 41 50" src="https://user-images.githubusercontent.com/85960512/235150223-167ee63c-e19f-4b60-9ba8-0148d5ca1ac3.png">

**Comment by christoph-menzi** [comment]
Es gibt ein Newsletter-Formular, das aber für die ganze Seitenfläche angedacht war. Man könnte es aber auch hier verwenden.

![image](https://user-images.githubusercontent.com/109087392/236760996-1f675a84-f00c-4705-994f-48094de1e237.png)

**Comment by christoph-menzi** [comment]
Wir können es auch als neue Variante anlegen und entsprechend stylen.

So war es angedacht:
![image](https://user-images.githubusercontent.com/109087392/236761222-e2899927-05a7-491d-8f73-6f6e14dd6c7b.png)

**Comment by mguddelmoni** [comment]
Es gibt nun neu diese Varianten
- Gross
- ohne Layout für iFrame
- Klein ohne PopUp (Neue Variante)
- Klein mit PopUp
- Fenster rechts
