### ISSUE TITLE
Team-Seite

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#80]
Die Kontaktdaten sind von der Grösse etwas komisch, wenn diese so viel kleiner sind.

<img width="974" alt="Bildschirm­foto 2023-04-27 um 01 13 25" src="https://user-images.githubusercontent.com/85960512/234722169-0d6b6b2a-6468-42b0-bf1a-f959fbe75488.png">

Könnte man die Bilder etwas grösser machen?

<img width="855" alt="Bildschirm­foto 2023-04-27 um 01 16 23" src="https://user-images.githubusercontent.com/85960512/234722447-e2ba5ad3-08d5-44d0-a3c7-f5890b8739b4.png">

**Comment by christoph-menzi** [comment]
Ist angepasst. Bilder der Mitarbeiter müssen entsprechend eher hoch zugeschnitten werden.

![image](https://user-images.githubusercontent.com/109087392/235090531-e191a2d4-665e-4b18-9181-fdb58c8e5de2.png)

**Comment by Riccardalina** [comment]
@christoph-menzi : Ich verstehe die Logik dahinter nicht, habe Flavio jetzt auch hoch zugeschnitten, das Bild hat aber nicht die gleiche Grösse wie bei Alex - was muss ich machen, damit alle Bilder die gleiche Grösse haben am schluss?

**Comment by christoph-menzi** [comment]
Das Bild wird neu auf ein vordefiniertes Format zugeschnitten.

![image](https://user-images.githubusercontent.com/109087392/235096678-cfeb92a0-941d-4091-827a-9ada9bab8730.png)
