### ISSUE TITLE
Letter Header

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#81]
Hier ist mir aufgefallen, dass die Schrift und die Buchstaben versetzt sind.

Da ihr mit Text arbeitet und die Bilder auf diese maskiert, könnte man versuchen den Versatz über die line-height zu fixen, ich hatte es mit 0.9 auf den Buchstaben versucht, aber in dem Fall weiss ich, dass es teilweise schwierig sein kann.

Aber es ist sehr cool, dass ihr die Buchstaben maskiert 👍🏻

---

Es wäre nice, wenn es etwa so aussehen würde:

<img width="1463" alt="Bildschirm­foto 2023-04-27 um 01 21 23" src="https://user-images.githubusercontent.com/85960512/234723187-8f82cf3f-99d9-4376-ad45-3bdfe068dcd9.png">

Aktuell ist die Ausrichtung so:

<img width="1461" alt="Bildschirm­foto 2023-04-27 um 01 21 30" src="https://user-images.githubusercontent.com/85960512/234723190-61db9217-f871-4633-b298-1a1c8b8186b1.png">

---

https://abonax2023.visions.page/angebot/fachbereiche/marketing-und-vertrieb.html

**Comment by alexanderbuergin** [comment]
Auf dieser Seite haben wir noch etwas Schwierigkeiten mit dem Text im Header.

https://abonax2023.visions.page/angebot/services/projektmanagement-digitalisierung.html

---

<img width="1473" alt="Bildschirm­foto 2023-04-28 um 11 45 05" src="https://user-images.githubusercontent.com/85960512/235115729-05167aa1-2534-45cd-828f-9a0645235dd2.png">

---

Würde es gehen, wenn die Content Area im Header auf 50% gestellt wäre?

<img width="1464" alt="Bildschirm­foto 2023-04-28 um 11 51 13" src="https://user-images.githubusercontent.com/85960512/235116380-c309e737-a80d-462b-bc25-2d66fc0fb86b.png">


<img width="1422" alt="Bildschirm­foto 2023-04-28 um 11 50 59" src="https://user-images.githubusercontent.com/85960512/235116375-b8653299-dd8b-40a7-aff6-21f86b6f45ef.png">

**Comment by christoph-menzi** [comment]
Ich habe nun 6 / 6 gemacht, also 50%

**Comment by mguddelmoni** [comment]
Buchstaben Versatz so gut es ging mit Line-Height abgefangen pro MediaBreakPoint
