### ISSUE TITLE
Logo Bande

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#82]
Die Logos sind sehr eng und gross dargestellt, hier sollten diese etwas kleiner sein und mit mehr Abstand zwischen diesen, es muss nicht so viel wie in der Vorlage sein, aber sicher 2 % mehr.

<img width="1475" alt="Bildschirm­foto 2023-04-27 um 01 26 49" src="https://user-images.githubusercontent.com/85960512/234723582-036b0121-eca5-4cfb-a20c-e1171ba53490.png">

<img width="944" alt="Bildschirm­foto 2023-04-27 um 01 26 41" src="https://user-images.githubusercontent.com/85960512/234723584-8dbd084a-46e4-4acb-ade8-37be093ef0e4.png">

**Comment by christoph-menzi** [comment]
Die Logos sind nun maximal 180px breit, werden dynamisch zentriert ausgerichtet (egal ob 3 oder 7 Logos)

![image](https://user-images.githubusercontent.com/109087392/235084984-8bd5d4cb-7a81-4a98-b2ea-8acc5686e48f.png)

**Comment by alexanderbuergin** [comment]
Gut, danke ;)
