### ISSUE TITLE
CTA: Button whitespace

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#83]
Bei den CTA Elementen hat der Button nach unten einen whitespace, wodurch der Abstand nach oben und unten nicht identisch ist

<img width="994" alt="Bildschirm­foto 2023-04-27 um 01 29 44" src="https://user-images.githubusercontent.com/85960512/234724003-5afa591d-708d-4770-839e-0ff2d7a4e0a8.png">

**Comment by christoph-menzi** [comment]
Ich sehe es nicht, kann es nicht reproduzieren. Welches OS? Welcher Browser? Welche Seite?

Chrome / Windows 11:
![image](https://user-images.githubusercontent.com/109087392/235075449-2f19d8d2-51a8-43f8-b32d-41d395d9b7a3.png)

Chrome / Mac (Ventura):
![image](https://user-images.githubusercontent.com/109087392/235075519-329760cd-f298-4c43-aa10-f3dd2581ba42.png)

**Comment by alexanderbuergin** [comment]
Auf deinem Screenshot sieht es richtig aus.

Beispielsweise hier:

https://abonax2023.visions.page/angebot/fachbereiche/waerme.html

Mac, Chrome (aktuelle Version, M1 Mac)

<img width="902" alt="Bildschirm­foto 2023-04-28 um 11 40 12" src="https://user-images.githubusercontent.com/85960512/235113720-4960c044-a85d-4328-9402-e8066432adc0.png">

**Comment by alexanderbuergin** [comment]
`button: display: flex` behebt das Problem in meinem Fall, aber: Ich habe das nur an dieser stelle genutzt, vielleicht zerreist dies etwas im Layout auf anderen pages.

<img width="959" alt="Bildschirm­foto 2023-04-28 um 11 42 07" src="https://user-images.githubusercontent.com/85960512/235114016-6e3908b1-e1fc-4ece-ae00-8ddff59f52e6.png">
<img width="913" alt="Bildschirm­foto 2023-04-28 um 11 41 41" src="https://user-images.githubusercontent.com/85960512/235114025-bccf8483-4397-4911-a20a-8dbe45e59722.png">

**Comment by christoph-menzi** [comment]
ok, ist gefixt.
