### ISSUE TITLE
Referenzen

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#84]
Auf der Referenzseite scheint der Wrapper für den Content sehr schmal zu sein. Dieser kann ruig 100% der breite einnehmen auf kleineren Bildschirmen, und nur auch grösseren kleiner sein

https://abonax2023.visions.page/referenzen/kunden/walenstadt.html

Vorlage:
<img width="559" alt="Bildschirm­foto 2023-04-27 um 01 31 23" src="https://user-images.githubusercontent.com/85960512/234724313-d9a94efa-2de8-46fa-a330-ccfb7b16e099.png">

Aktuell:

<img width="1473" alt="Bildschirm­foto 2023-04-27 um 01 31 33" src="https://user-images.githubusercontent.com/85960512/234724301-02e8845c-3abb-48d6-b5f0-4773562b304b.png">

**Comment by christoph-menzi** [comment]
Ist nun breiter.

![image](https://user-images.githubusercontent.com/109087392/235073396-2d9ce392-948a-4be5-ba65-1b8b4e16386e.png)

**Comment by alexanderbuergin** [comment]
Sehr gut, danke.

Könnte man hier das Spacing oben und unten gleich setzen? Und den Haupttitel Mehr Artikel für dich einen Ticken kleiner? Eine H-Grösse kleiner.

Sind die weiteren Artikel dynamisch?

<img width="1472" alt="Bildschirm­foto 2023-04-28 um 11 34 03" src="https://user-images.githubusercontent.com/85960512/235112284-f7e9ce9b-87fd-4e60-8490-2d99de1cfbac.png">

**Comment by christoph-menzi** [comment]
Die  Abstände sind 120px (abzüglich Padding von Bootstrap-Raster. Was meinst Du mit Abstand nach unten? Welcher Abstand?
![image](https://user-images.githubusercontent.com/109087392/235113737-f4c72efc-1714-460a-b212-f26ab999ecc7.png)

Und ja, die Inhalte werden dynamisch geladen. Man könnte noch definieren wie es genau funktionieren soll. Die aktuellsten 3 Artikel?

Titel ist ein nun h4 gross, also eine stufe kleiner.

**Comment by alexanderbuergin** [comment]
Ich meinte die Abstände unten bei dem weiteren Artikel. Bei mir ist der Abstand unten etwa 2x so gross wie der nach oben.

Bei der More Actricles Section unten auf der Artikelseite.

**Comment by christoph-menzi** [comment]
ah ok, unten ist der Abstand wie oben.
