### ISSUE TITLE
Angebotsseite

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#85]
Der Scroll to top funktioniert bei mir nicht. Opera/Chrome auf dem M1 in der aktuellen Version

Auch die Scroll to Anchor Links wollen bei mir nicht.

<img width="1357" alt="Bildschirm­foto 2023-04-27 um 01 34 12" src="https://user-images.githubusercontent.com/85960512/234724526-a24760c2-5f3a-46a3-a35b-1b93931b4bca.png">

---

In diesem Layout müssten die CTAs kleiner sein, heisst weniger Abstände und eventuell eine etwas kleinere Schrift.

<img width="741" alt="Bildschirm­foto 2023-04-27 um 01 34 23" src="https://user-images.githubusercontent.com/85960512/234724612-5e3941d6-02dc-473c-a2e0-860772b0c694.png">

---

Unten schliessen die Inhalte nicht mit dem Footer ab, bei fast allen Seiten stimmt es aber :)

<img width="739" alt="Bildschirm­foto 2023-04-27 um 01 34 40" src="https://user-images.githubusercontent.com/85960512/234724663-5daedb40-c5e5-41a4-bcf7-8742556dd9dd.png">

---

Bei den kleineren Bildschirmen nimmt man hier die Abstände rechts besser weg. Nur bei den grossen lassen 1800+

<img width="729" alt="Bildschirm­foto 2023-04-27 um 01 39 23" src="https://user-images.githubusercontent.com/85960512/234725072-38328e23-3498-4586-af37-7245c7a92ec1.png">

Selben gilt für die Linke Seiten-Seite

<img width="825" alt="Bildschirm­foto 2023-04-27 um 01 41 47" src="https://user-images.githubusercontent.com/85960512/234725375-aa0762ad-adc8-47b6-bc0e-9a94139cab52.png">

**Comment by christoph-menzi** [comment]
Der Abstand kann definiert werden.

![image](https://user-images.githubusercontent.com/109087392/235142942-a6c7efdb-7d33-411d-9ef2-9bb8f21d0c3c.png)

Anker funktioniert bei mir MAC und PC. @mguddelmoni Kannst Du das bitte nochmals gegenprüfen? Vielen Dank.

**Comment by alexanderbuergin** [comment]
Könntet ihr nicht überall einen Standardabstand hinterlegen und wenn man diesen nicht ändert, alle Abstände identisch sind? So mache ich das meistens.

**Comment by christoph-menzi** [comment]
Der Standard ist immer 120px. Das lässt sich dann aber nicht immer einfach so handeln. Es gibt auch Elemente die weniger Abstand haben. Und es gibt Layouts mit Hintergrundfarben, die dann oben wieder Abstand brauchen.

**Comment by christoph-menzi** [comment]
Abstand Links und Rechts wird nun bei einer Grösse kleiner als 1700px auf 0 gesetzt.

@include media-breakpoint-down(xxxl)

**Comment by christoph-menzi** [comment]
@mguddelmoni  
Anker funktioniert bei mir (Windows/Mac via Browserstack), bitte gegenprüfen.

**Comment by mguddelmoni** [comment]
Getestet mit Browserstack:

- Windows Safari 16.3
- Windows Firefox 112
- Windows Chrome 112
- Windows Opera 98
- Windows Edge 112
- Mac Safari 15.2
- Mac Chrom 113.0
- Mac Firefox 112.0.2

Funktioniert auf allen aktuellen Browsern und Betriebssystemen.
Der Fehler ist nicht reproduzierbar.
