### ISSUE TITLE
Listenpunkte

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#86]
Könntet ihr die Listenpunkte noch einheitlich einstellen? Danke.

<img width="686" alt="Bildschirm­foto 2023-04-27 um 01 43 40" src="https://user-images.githubusercontent.com/85960512/234725541-b8e33b7b-a768-40ab-814f-0bcd81179fa4.png">

<img width="792" alt="Bildschirm­foto 2023-04-27 um 01 43 22" src="https://user-images.githubusercontent.com/85960512/234725547-e5bbe088-31eb-485e-8f34-25f749fea481.png">

**Comment by christoph-menzi** [comment]
Ist angepasst.

![image](https://user-images.githubusercontent.com/109087392/235072694-6cbf178c-cb57-43e4-8c92-545fe69eb8d1.png)

**Comment by alexanderbuergin** [comment]
Hallo Christian,

bitte in die andere Richtung. Also, dass alle das grüne Quadrat haben. Ich habe mich da wohl nicht gut ausgedrückt, bitte entschuldige.

**Comment by christoph-menzi** [comment]
Gut habe ich noch ein Backup. :-) Kein Problem, ist nun umgebaut.

![image](https://user-images.githubusercontent.com/109087392/235112747-de7eae8d-b594-4a99-8024-bab0bb245243.png)
![image](https://user-images.githubusercontent.com/109087392/235112783-a8a3fb8a-4800-448d-82c5-7027c36db62d.png)

**Comment by alexanderbuergin** [comment]
Danke 👌🏻
