### ISSUE TITLE
Fade In Trigger

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#87]
Beim FaceIn/SlideIn effekt der Texte ist mit noch etwas aufgefallen:

https://user-images.githubusercontent.com/85960512/235116537-b708100d-6e0e-4232-86f6-512b7de1ff1b.mov

Wäre es möglich, den Trigger für den Effekt früher zu setzen?

**Comment by christoph-menzi** [comment]
Es gibt die Option um die Animaiton früher zu starten. Standard ist 120, ich habe es nun auf 80 angepasst.

offset: 120, // offset (in px) from the original trigger point
