### ISSUE TITLE
Video Element: Abstand zu Text

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#88]
Der Abstand zwischen Video und Titel ist hier grösser als auf der Vorlage. Ausserdem scheint das ein anderer Schrifttyp zu sein im Titel?

![image](https://user-images.githubusercontent.com/122005698/235137749-111d0b26-065a-42ef-b300-9ae5364ab2a5.png)

Vorlage:
![image](https://user-images.githubusercontent.com/122005698/235137818-76ed0711-38ea-4328-a6f0-72256bb361f1.png)

**Comment by christoph-menzi** [comment]
Der Abstand kann definiert werden.

![image](https://user-images.githubusercontent.com/109087392/235140504-f284dc6a-e2f0-49fd-8d02-5db585a2d938.png)

Headline ebenfalls.

**Comment by christoph-menzi** [comment]
Wenn möglich bitte im ein Beispiel-Link angeben, vielen Dank.
