### ISSUE TITLE
Events: Darstellung Datum

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#89]
Hier ist stimmt etwas mit dem Punkt beim Monat nicht. Kann man den Monat nicht ausschreiben?

![image](https://user-images.githubusercontent.com/122005698/235142516-02cdc3ec-9d53-4b78-87cf-b7813b8bcf5e.png)

**Comment by christoph-menzi** [comment]
Habe ich DIr angepasst. So okey?

![image](https://user-images.githubusercontent.com/109087392/235143825-f234e2ac-f660-4c25-820c-5bf1630b153c.png)

**Comment by Riccardalina** [comment]
hm also jetzt hat es halt einfach keinen punkt mehr und der monat ist auch nicht ausgeschrieben. entweder machen wir einen punkt direkt hinter den gekürzten monat ohne leerschlag dazwischen oder wir schreiben den monat aus...

**Comment by Riccardalina** [comment]
ausserdem müsste ich auf der detailseite noch die uhrzeiten angeben können, finde dazu keine funktion.

![image](https://user-images.githubusercontent.com/122005698/235144339-3eb47ad4-fa25-4279-ba9c-1d679fbce556.png)

**Comment by Riccardalina** [comment]
ausserdem fehlt mir hier die möglichkeit weitere inhalte hinzuzfügen:

![image](https://user-images.githubusercontent.com/122005698/235144594-1fb7e4a1-9d8a-49a9-9bfb-735719631ab1.png)


eigentlich müsste ich hier noch mehr erfassen können:
https://xd.adobe.com/view/a073a1cb-caa3-4129-9326-cc28bde3d14f-f520/screen/b6b99847-07a8-44a7-9298-4612a5fc56b5

Beispiellink: https://abonax2023.visions.page/events/event-daten/abonax-bbq-2022-2.html

**Comment by christoph-menzi** [comment]
Monat ausgeschrieben:
![image](https://user-images.githubusercontent.com/109087392/235144765-5ee2f456-f904-45be-be31-ca86f29600a8.png)

**Comment by christoph-menzi** [comment]
Für die Eventseite gibt es eine ContentBlocks Vorlage:

![image](https://user-images.githubusercontent.com/109087392/235145672-7dca1c22-b32c-476c-a851-4de2633db616.png)

Falls mal Contentblocks nicht verfügbar ist:
![image](https://user-images.githubusercontent.com/109087392/235145760-36ce7fdc-480a-4dbb-9774-9a5ea3f565bf.png)

**Comment by christoph-menzi** [comment]
> ausserdem müsste ich auf der detailseite noch die uhrzeiten angeben können, finde dazu keine funktion.
> 
> ![image](https://user-images.githubusercontent.com/122005698/235144339-3eb47ad4-fa25-4279-ba9c-1d679fbce556.png)

Würde ein Textfeld reichen?

**Comment by Riccardalina** [comment]
> > ausserdem müsste ich auf der detailseite noch die uhrzeiten angeben können, finde dazu keine funktion.
> > ![image](https://user-images.githubusercontent.com/122005698/235144339-3eb47ad4-fa25-4279-ba9c-1d679fbce556.png)
> 
> Würde ein Textfeld reichen?

Ja das würde reichen

> Für die Eventseite gibt es eine ContentBlocks Vorlage:
> 
> ![image](https://user-images.githubusercontent.com/109087392/235145672-7dca1c22-b32c-476c-a851-4de2633db616.png)
> 
> Falls mal Contentblocks nicht verfügbar ist: ![image](https://user-images.githubusercontent.com/109087392/235145760-36ce7fdc-480a-4dbb-9774-9a5ea3f565bf.png)

ok aber ich kann kein layout hinzufügen

**Comment by Riccardalina** [comment]
> > ausserdem müsste ich auf der detailseite noch die uhrzeiten angeben können, finde dazu keine funktion.
> > ![image](https://user-images.githubusercontent.com/122005698/235144339-3eb47ad4-fa25-4279-ba9c-1d679fbce556.png)
> 
> Würde ein Textfeld reichen?

ja das würde reichen :-)

**Comment by Riccardalina** [comment]
> Für die Eventseite gibt es eine ContentBlocks Vorlage:
> 
> ![image](https://user-images.githubusercontent.com/109087392/235145672-7dca1c22-b32c-476c-a851-4de2633db616.png)
> 
> Falls mal Contentblocks nicht verfügbar ist: ![image](https://user-images.githubusercontent.com/109087392/235145760-36ce7fdc-480a-4dbb-9774-9a5ea3f565bf.png)

top! das kannte ich noch nicht :-) danke!

**Comment by Riccardalina** [comment]
Ich muss bei der Agenda auch externe Speaker erfassen können und möchte dafür nicht immer einen neuen Mitarbeitenden erfassen:

![image](https://user-images.githubusercontent.com/122005698/235147573-96dfdf9b-fcfa-49c6-81d8-c08b39046e40.png)

**Comment by Riccardalina** [comment]
ausserdem sieht das anders aus als auf der vorlage bzgl. Name und Firma, Zeilenstriche, Abstände....

![image](https://user-images.githubusercontent.com/122005698/235147734-66f06036-9784-4f3b-91b9-62e72150e81f.png)


Vorlage:
![image](https://user-images.githubusercontent.com/122005698/235147822-2f0bd6ce-19ff-4ff0-86c7-ad06dab994bd.png)

**Comment by christoph-menzi** [comment]
> > > ausserdem müsste ich auf der detailseite noch die uhrzeiten angeben können, finde dazu keine funktion.
> > > ![image](https://user-images.githubusercontent.com/122005698/235144339-3eb47ad4-fa25-4279-ba9c-1d679fbce556.png)
> > 
> > 
> > Würde ein Textfeld reichen?
> 
> ja das würde reichen :-)

![image](https://user-images.githubusercontent.com/109087392/235149426-49fe62ff-bb27-48fc-870b-e1ff14763f1b.png)

**Comment by christoph-menzi** [comment]
Darstellung habe ich angepasst. Abstand nach oben/unten, Linien bei jedem Element.

**Comment by christoph-menzi** [comment]
> Ich muss bei der Agenda auch externe Speaker erfassen können und möchte dafür nicht immer einen neuen Mitarbeitenden erfassen:
> 
> ![image](https://user-images.githubusercontent.com/122005698/235147573-96dfdf9b-fcfa-49c6-81d8-c08b39046e40.png)

Würd hier auch ein Textfeld ohne Verlinkung reichen?

**Comment by Riccardalina** [comment]
> > Ich muss bei der Agenda auch externe Speaker erfassen können und möchte dafür nicht immer einen neuen Mitarbeitenden erfassen:
> > ![image](https://user-images.githubusercontent.com/122005698/235147573-96dfdf9b-fcfa-49c6-81d8-c08b39046e40.png)
> 
> Würd hier auch ein Textfeld ohne Verlinkung reichen?

Ja das würde reichen, ich muss nur den Vornamen, Namen und die Firma des Speakers angeben können

**Comment by christoph-menzi** [comment]
Dann braucht es da grundsätzlich keine Mitarbeiter Auswahl, sondern nur ein Textfeld für die freie Eingabe, Korrekt?
Somit würde ich das Auswahlfeld entfernen und nur ein Textfeld bereitstellen.

**Comment by Riccardalina** [comment]
> Dann braucht es da grundsätzlich keine Mitarbeiter Auswahl, sondern nur ein Textfeld für die freie Eingabe, Korrekt? Somit würde ich das Auswahlfeld entfernen und nur ein Textfeld bereitstellen.

genau so ist es

**Comment by christoph-menzi** [comment]
> Ich muss bei der Agenda auch externe Speaker erfassen können und möchte dafür nicht immer einen neuen Mitarbeitenden erfassen:
> 
> ![image](https://user-images.githubusercontent.com/122005698/235147573-96dfdf9b-fcfa-49c6-81d8-c08b39046e40.png)

Ist umgebaut. Neu ist es nur noch ein Textfeld:
https://abonax2023.visions.page/events/event-daten/abonax-bbq-2022-2.html

![image](https://user-images.githubusercontent.com/109087392/235181532-81c9ab0e-cc1e-49f2-bf1b-292d216aba56.png)
