### ISSUE TITLE
Navigation: Icon Grössen

### ISSUE THREAD

**Issue by alexanderbuergin** [Riccardalina/Abonax-Website#9]
Die Icons in der Navigation passen von der Grösse nicht ganz:

<img width="334" alt="Bildschirm­foto 2023-02-16 um 09 50 06" src="https://user-images.githubusercontent.com/85960512/219320298-3c37964e-40a5-417d-8c9f-df19f5ebc4fb.png">

**Comment by mguddelmoni** [comment]
Bitte den Cache löschen oder im inkognito Modus testen. Dieses issue ist seit Mittwoch letzte Woche gelöst.
