### ISSUE TITLE
Events: Spacing in der Übersicht

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#90]
Sobald ich die Details anzeigen lasse (Link mit mehr Infos) ist der Abstand unten nicht mehr gleich gross wie der oben. Kann sich das nicht automatisch ausmitten?

![image](https://user-images.githubusercontent.com/122005698/235143138-8831fea1-6d9e-4c74-9d5f-debe0345ec03.png)

**Comment by christoph-menzi** [comment]
Abstand angepasst.

![image](https://user-images.githubusercontent.com/109087392/235144426-32cd6c12-ff0b-4307-808d-56d6de1d2739.png)
