### ISSUE TITLE
Events: Unterseite

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#91]
Wenn ich beim Richtext einen Link ergänzte, passiert irgendwas mit den Spacings und dem Header darüber. Ausserdem kann ich das Bild nicht einpassen, muss ich das bereits mit einer bestimmten Grösse hochladen oder gibt es eine Crop-Funktion dafür? Zudem hat das Bild einen Link obwohl im Backend nichts gesetzt wurde. Die Linkfunktion benötige ich eigentlich auch nicht.

![image](https://user-images.githubusercontent.com/122005698/235166856-a972d1d3-d698-44fc-894a-8dbc70761f1d.png)

Link: https://abonax2023.visions.page/events/event-daten/abonax-bbq-2022-2.html

Zudem müsste ich den Text hier auch noch mehr nach links einschieben können:

![image](https://user-images.githubusercontent.com/122005698/235169471-45d4f993-bf36-4e3d-8db5-22e31ec7c30f.png)

Vorlage:
![image](https://user-images.githubusercontent.com/122005698/235169603-110213d2-921f-4a63-a835-1895a33369bf.png)

**Comment by christoph-menzi** [comment]
Es gibt nun auch beim einspaltigen Layout die Möglichkeit links / rechts einzurücken.

Alternativ könntest Du auch ein 3 Spaltiges Layout nehmen und dann links/rechts 1-2 spalten verwenden.

Zudem kannst Du nun bei den Cards den Bildausschnittt vom Bild definieren.

![image](https://user-images.githubusercontent.com/109087392/235178793-d7e9387d-50bc-4832-adc6-e7635d5f0312.png)

**Comment by christoph-menzi** [comment]
Wenn das mit dem Abstand für Dich so okey ist, dann würde ich es wieder in dei Layoutvorlage übernehmen. Falls nicht, müsste man es auf ein 3 Spaltiges Layout umbauen

**Comment by Riccardalina** [comment]
top das passt so... jetzt ist aber neu kein abstand mehr zwischen bild und header/name des speakers - kannst du das bitte anschauen? ausserdem wäre es gut, wenn der untertitel hier noch grösser dargestellt wird, so ist er ein wenig gar klein.. vielleicht gross und fett aber kleiner als der titel oben und in grün? zudem ist das bild verpixelt obwohl es eine gute qialität haben sollte:

![image](https://user-images.githubusercontent.com/122005698/235418930-e0e849be-de05-4fde-a2c3-16fe1a1007b0.png)

**Comment by christoph-menzi** [comment]
Titel ist grösser:

![image](https://user-images.githubusercontent.com/109087392/236764349-edb05376-0a48-486a-9444-a096810f8c5d.png)

**Comment by christoph-menzi** [comment]
Alle Speaker haben nun einen einheitlichen Abstand:

![image](https://user-images.githubusercontent.com/109087392/236764415-fffd737c-caa9-4fe8-9b45-58eb0caa541b.png)
