### ISSUE TITLE
Element: Karten

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#92]
Der Abstand zwischen Bild und Header ist zu klein:

![image](https://user-images.githubusercontent.com/122005698/235443920-860f9a72-eca0-447a-aac3-124e78daded9.png)

LInk: https://abonax2023.visions.page/angebot/fachbereiche/energiewirtschaft.html

**Comment by Riccardalina** [comment]
habe hier den fehler nochmals entedeckt. irgendwie scheint bei den neu hinzugefügten Karten das Bild grösser zugeschnitten zu werden.

![image](https://user-images.githubusercontent.com/122005698/236157917-e4d22151-64ca-4e44-8a09-461f56be8fe1.png)

Link: https://abonax2023.visions.page/angebot/services/netzwirtschaft.html

**Comment by christoph-menzi** [comment]
Entweder wurde das von Mirko schon gefixt. Ich kann es nicht reproduzieren. Egal wie ich die Seite anzeigen lassen, egal welcher Browser ich verwende oder OS (Win/Mac).

Hast Du mir da weitere Informationen? Oder liegts an Deinem Browser-Cache?

**Comment by Riccardalina** [comment]
ja es scheint mittlerweile behoben zu sein :-) ich schliesse das ticket
