### ISSUE TITLE
Hintergrundfarbe

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#93]
Wieso ist hier ein schmaler Streifen weiss? Ich finde den Fehler nicht.

![image](https://user-images.githubusercontent.com/122005698/235451261-321ec494-5b97-47ee-aa90-f05452759d0c.png)

Link: https://abonax2023.visions.page/angebot/services/energiewirtschaft-neu.html

**Comment by christoph-menzi** [comment]
Ich finde die Stelle nicht. Bei mir wird alles korrekt angezeigt. Wurde der Fehler schon behoben? Evtl. durch Mirko?
Scheint aber eine Einstellung zu sein.
