### ISSUE TITLE
Element: Violette Box mit Buchstabe

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#95]
Die Bilder im Hintergrund sind wieder unscharf. Das Problem wurde eigentlich schon einmal gelöst?

![image](https://user-images.githubusercontent.com/122005698/236387637-fd40e0eb-c66d-4ddd-ae26-8e2393282469.png)

Beispiel: https://abonax2023.visions.page/angebot/services/business-development.html

**Comment by christoph-menzi** [comment]
Die Bildkomprimierung war nur auf einer Seite aktiv, hatte ich nicht bemerkt. Ist nun angepasst.

Wichtig: Das Bild muss nochmals zugeschnitten werden.

![image](https://user-images.githubusercontent.com/109087392/236459273-73d1083d-0d7c-4421-a8b8-2b80501a91a2.png)
