### ISSUE TITLE
Abstände im Richtext

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#96]
In allen Elementen die einen Richtext haben, ist der Abstand zwischen Aufzählung und nachfolgendem Text immer etwas unschön und passt nicht ins Bild. Ohne einen Absatz ist der Abstand zu klein und mit einem Absatz ist er zu gross. Bitte in allen Elementen, die Richtext haben, anpassen.

![image](https://user-images.githubusercontent.com/122005698/236409733-d672ab72-e48d-47d8-a27f-7d897b5fe591.png)

Beispiel: https://abonax2023.visions.page/angebot/services/business-development.html

**Comment by christoph-menzi** [comment]
Die Abstände sind nun vereinheitlicht.

![image](https://user-images.githubusercontent.com/109087392/236457411-0d81f3b1-bbf2-4dc9-80a8-0fbd4d0efdf2.png)
