### ISSUE TITLE
Denkfabrik: Bewertungsfunktion

### ISSUE THREAD

**Issue by Riccardalina** [Riccardalina/Abonax-Website#97]
Die Bewertungsfunktion in der Denkfabrik bei den Innovationen scheint nicht zu funktionieren. Bitte prüfen.
Link: https://abonax2023.visions.page/manager/?a=resource/update&id=98

Ausserdem hat es in der Kommentarspalte noch einen Grammatikfehler:
![Test](https://user-images.githubusercontent.com/122005698/236782838-0a832bf2-0fb8-4bd7-87fc-da540ac8f48c.png)

**Comment by alexanderbuergin** [comment]
@Riccardalina Sendest du mir noch ein Login für den Member Bereich?

**Comment by mguddelmoni** [comment]
Bitte eine präzise Beschreibung was genau bei der Bewertung nicht funktioniert. 
Ich sehe die Bewertungen alle in der Datenbank im Backend und das bewerten verändert die Matrix korrekt nach Vorgabe.

**Comment by Riccardalina** [comment]
> Bitte eine präzise Beschreibung was genau bei der Bewertung nicht funktioniert. Ich sehe die Bewertungen alle in der Datenbank im Backend und das bewerten verändert die Matrix korrekt nach Vorgabe.

Wenn ich hier: https://abonax2023.visions.page/abonax-club/abonax-denkfabrik/emil-die-alternative-zu-ecarup.html die Bewertung ändere, ändert sich in der Matrix nichts.

**Comment by Riccardalina** [comment]
> @Riccardalina Sendest du mir noch ein Login für den Member Bereich?

BN: abonax23
PW: abonax23

**Comment by mguddelmoni** [comment]
Der Reload hat nicht funktioniert. Die Bewertung war erst nach dem aktualisieren der Seite sichtbar. 
Ist jetzt behoben.
